package br.com.cs.controlmoto.view;

import java.awt.Color;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.MaskFormatter;
import javax.swing.text.PlainDocument;

class CadMotoristaView extends JInternalFrame implements ActionListener, FocusListener, KeyListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3322519713845032454L;

	JLabel	lblCodigo,lblNome,lblRg,lblCpf,lblHabilitacao,lblCategoria,lblVencimento,lblDatanascimento,lblEndereco,lblNumero,lblBairro,lblCidade,lblEstado,lblCep,lblContato,
			lblTelefone,lblCelular,lblBanco,lblConta,lblAgencia,lblTipo,lblComissao,lblDatacadastro,lblInfoGerais,lblInfoEndereco,lblInfoContato,lblInfoBanco;

	JTextField	txtCodigo,txtNome,txtEndereco,txtNumero,txtBairro,txtCidade,txtEstado,txtContato,txtBanco,txtConta,txtAgencia,txtTipo,txtComissao,txtDataCadastro;

	JComboBox jcbTipoConta, jcbTipoEstado, jcbTipoBanco,jcbCategoria;

	JFormattedTextField JtxtCodigo,JtxtRg,JtxtCpf,JtxtHabilitacao,JtxtVencimento,JtxtDataNascimento,JtxtCep,JtxtTelefone,JtxtCelular,JtxtDatacadastro;//JtxtCategoria,
	
	JSeparator jsInfoGerais,jsInfoEndereco,jsInfoContato,jsInfoBanco;

	JButton btoIncluir,btoLocalizar,btoGravar,btoExcluir,btoSair,btoAtualizar,btoCancelar;
	
	private ControlMotoView telaControlMoto;

	String [] tipoBanco = {"","BMG","BOAVISTA","BANKBOSTON","BRASIL","BRADESCO","CACIQUE","CAIXA ECONOMICA FEDERAL","CIDADE","CITIBANK","BANESPA","EXCEL BANCO","FININVEST","FRANCES E BRASILEIRO","HSBC","ITAU","FINASA",
			"NOSSA CAIXA NOSSO BANCO","PANAMERICANO","PAULISTA","REAL","RURAL","SAFRA","BANCO DE SANTANDER","SANTISTA","SCHAIN CURY","SOFISA","SUDAMERIS BRASIL","SUMITOMO BRASILEIRO","TOKYO","UNIBANCO","VOTORANTIM"};
	String [] tipoConta = {"","CORRENTE","POUPANÇA"};
	String [] tipoEstado = {"","AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR",
			"PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"};
	String [] categoria = {"","A","B","C","D"};

	String separadorPath = "", comiss = "";
	Double comis, comissa;
	NumberFormat comissao;

	Connection minhaConexao;
	Statement minhaSTM;
	ResultSet rs;
	
	Date data, dataN, dataV;
    SimpleDateFormat sdf,sdfTimestamp;
    Timestamp timestamp,timestampN,timestampV;
    java.sql.Date dt;    
    int enderecoPk, telefonePk;
    //Serve para mover a tela interna
    static int openFrameCount = 2;
    static final int xOffset = 35, yOffset = 30;
	
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
	public CadMotoristaView(String titulo, ControlMotoView controlMoto){
    	super(titulo,false,true,false,true);
    	setSize(680,570);
    	setVisible(true);
    	setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
    	separadorPath = System.getProperty("file.separator");
//		ImageIcon icone = new ImageIcon("..//ControlMoto/imagens/logo_cs_b.gif");
//		ImageIcon icone = new ImageIcon(".."+separadorPath+separadorPath+"ControlMoto"+separadorPath+"imagens"+separadorPath+"logo_cs_b.gif");
//		setIconImage(icone.getImage());
    	
    	this.telaControlMoto = telaControlMoto;
    	controlMoto.jDesktopPane.add(this);

		GridBagConstraints cons = new GridBagConstraints();
		Container CadSer = getContentPane();
		GridBagLayout layout = new GridBagLayout();
		CadSer.setLayout(layout);

		cons.insets = new Insets (3,5,3,5); 
		cons.weightx = 0.30;cons.weighty = 0.30;

		comissao = NumberFormat.getNumberInstance(new Locale("",""));
		comissao.setMinimumFractionDigits(2);comissao.setMaximumFractionDigits(2);

		lblCodigo = new JLabel("Código");lblNome = new JLabel("Nome");lblRg = new JLabel("RG");lblCpf = new JLabel("CPF");
		lblHabilitacao = new JLabel("Habilitação");lblCategoria = new JLabel("Categoria");lblVencimento = new JLabel("Vencimento");
		lblDatanascimento = new JLabel("Data de Nascimento");lblEndereco = new JLabel("Endereço");lblNumero = new JLabel("Número");
		lblBairro = new JLabel("Bairro");lblCidade = new JLabel("Cidade");lblEstado = new JLabel("Estado");lblCep = new JLabel("CEP");
		lblTelefone = new JLabel ("Telefone");lblCelular = new JLabel("Celular");lblBanco = new JLabel("Banco");lblAgencia = new JLabel("Agência");
		lblConta = new JLabel("Conta Número");lblTipo = new JLabel("Tipo da Conta");lblComissao = new JLabel("Comissão");lblDatacadastro = new JLabel("Data do Cadastro");
		lblInfoGerais = new JLabel("Informações Gerias");lblInfoEndereco = new JLabel("Informações de Localização");
		lblInfoContato = new JLabel("Informações de Contato");lblInfoBanco = new JLabel("Informações Bancária");

		txtCodigo = new JTextField();txtCodigo.setDocument(new MeuDocument());
		txtNome = new JTextField();txtNome.setDocument(new MeuDocument());
		txtEndereco = new JTextField();txtEndereco.setDocument(new MeuDocument());
		txtNumero = new JTextField();txtNumero.setDocument(new MeuDocument());
		txtBairro = new JTextField();txtBairro.setDocument(new MeuDocument());
		txtCidade = new JTextField();txtCidade.setDocument(new MeuDocument());
		txtEstado = new JTextField();txtEstado.setDocument(new MeuDocument());
		txtBanco = new JTextField();txtBanco.setDocument(new MeuDocument());
		txtAgencia = new JTextField();txtConta = new JTextField();
		txtTipo = new JTextField();txtTipo.setDocument(new MeuDocument());
		txtComissao = new JTextField();txtComissao.setDocument(new MeuDocument());
		txtDataCadastro = new JTextField();txtDataCadastro.setDocument(new MeuDocument());

		jcbTipoConta = new JComboBox(tipoConta);

		JtxtCodigo = new JFormattedTextField(setMascara("### ####"));
		JtxtRg = new JFormattedTextField(setMascara("##.###.###-#"));
		JtxtCpf = new JFormattedTextField(setMascara("###.###.###-##"));
		JtxtHabilitacao = new JFormattedTextField(setMascara("##.###.###.###"));
//		JtxtCategoria = new JFormattedTextField(setMascara("##.###"));
		JtxtVencimento = new JFormattedTextField(setMascara("##/##/####"));
		JtxtDataNascimento = new JFormattedTextField(setMascara("##/##/####"));
		JtxtCep = new JFormattedTextField(setMascara("#####-###"));
		JtxtTelefone = new JFormattedTextField(setMascara("(##) ####-####"));
		JtxtCelular = new JFormattedTextField(setMascara("(##) ####-####"));
//		JtxtDatacadastro = new JFormattedTextField(setMascara("##/##/####"));
		
		jcbTipoBanco = new JComboBox(tipoBanco);
		jcbTipoConta = new JComboBox(tipoConta);
		jcbTipoEstado = new JComboBox(tipoEstado);
		jcbCategoria = new JComboBox(categoria);
		
		jsInfoGerais = new JSeparator();jsInfoEndereco = new JSeparator();jsInfoContato = new JSeparator();
		jsInfoBanco = new JSeparator();
		

//		jXDPDataCadastro = new JXDatePicker();

		btoIncluir = new JButton("Incluir");btoIncluir.setMnemonic(KeyEvent.VK_I);
		btoLocalizar = new JButton("Localizar");btoLocalizar.setMnemonic(KeyEvent.VK_L);
		btoGravar = new JButton("Gravar");btoGravar.setMnemonic(KeyEvent.VK_G);
		btoExcluir =  new JButton("Excluir");btoExcluir.setMnemonic(KeyEvent.VK_E);
		btoSair = new JButton("Sair");btoSair.setMnemonic(KeyEvent.VK_S);
		btoAtualizar = new JButton("Atualizar");btoAtualizar.setMnemonic(KeyEvent.VK_A);
		btoCancelar = new JButton("Cancelar");btoCancelar.setMnemonic(KeyEvent.VK_C);
		
		sdf = new SimpleDateFormat("dd/MM/yyyy");

		cons.anchor = GridBagConstraints.NORTHWEST;

		/*
		 * INFORMAÇÕES GERAIS DO MOTORISTAS COMO NOME, DOCUMENTOS, PLACA DO VEÍCULO
		 */
		cons.gridx = 1;cons.gridy = 1;cons.gridwidth = 3;cons.ipadx = 70;
		lblInfoGerais.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblInfoGerais.setForeground(Color.BLUE);
		CadSer.add(lblInfoGerais,cons);
		cons.gridx = 1;cons.gridy = 2;cons.gridwidth = 10;cons.ipadx = 550;
		CadSer.add(jsInfoGerais,cons);
				
		cons.gridx = 1;cons.gridy = 3;cons.gridwidth = 2;cons.ipadx = 30;
		CadSer.add(lblCodigo,cons);
		cons.gridx = 2;cons.gridy = 3;cons.gridwidth = 2;cons.ipadx = 80;cons.ipady = 1;
		txtCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(txtCodigo,cons);txtCodigo.setNextFocusableComponent(txtNome);
		txtCodigo.addFocusListener(this);

		cons.gridx = 1;cons.gridy = 4;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblNome,cons);
		cons.gridx = 2;cons.gridy = 4;cons.gridwidth = 9;cons.ipadx = 450;
		CadSer.add(txtNome,cons);txtNome.setNextFocusableComponent(JtxtRg);
		txtNome.addFocusListener(this);

		cons.gridx = 1;	cons.gridy = 5;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblRg,cons);
		cons.gridx = 2;cons.gridy = 5;cons.gridwidth = 2;cons.ipadx = 110;
		JtxtRg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtRg,cons);JtxtRg.setNextFocusableComponent(JtxtCpf);
		JtxtRg.addFocusListener(this);

		cons.gridx = 6;cons.gridy = 5;cons.gridwidth = 1;cons.ipadx = 20;
//		lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblCpf,cons);
		cons.gridx = 7;cons.gridy = 5;cons.gridwidth = 2;cons.ipadx = 110;
		JtxtCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtCpf,cons);JtxtCpf.setNextFocusableComponent(JtxtHabilitacao);
		JtxtCpf.addFocusListener(this);

		cons.gridx = 1;cons.gridy = 6;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblHabilitacao,cons);
		cons.gridx = 2;cons.gridy = 6;cons.gridwidth = 2;cons.ipadx = 110;
		JtxtHabilitacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtHabilitacao,cons);JtxtHabilitacao.setNextFocusableComponent(jcbCategoria);
		JtxtHabilitacao.addFocusListener(this);

		cons.gridx = 6;cons.gridy = 6;cons.gridwidth = 1;cons.ipadx = 20;
//		lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblCategoria,cons);
		cons.gridx = 7;cons.gridy = 6;cons.gridwidth = 2;cons.ipadx = 75;
		CadSer.add(jcbCategoria,cons);jcbCategoria.setNextFocusableComponent(JtxtVencimento);
		jcbCategoria.addFocusListener(this);

		cons.gridx = 1;cons.gridy = 7;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblVencimento,cons);
		cons.gridx = 2;cons.gridy = 7;cons.gridwidth = 2;cons.ipadx = 110;
		JtxtVencimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtVencimento,cons);JtxtVencimento.setNextFocusableComponent(JtxtDataNascimento);
		JtxtVencimento.addFocusListener(this);

		cons.gridx = 6;cons.gridy = 7;cons.gridwidth = 1;cons.ipadx = 20;
//		lblDatanascimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblDatanascimento,cons);
		cons.gridx = 7;cons.gridy = 7;cons.gridwidth = 2;cons.ipadx = 110;
		JtxtDataNascimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtDataNascimento,cons);JtxtDataNascimento.setNextFocusableComponent(txtComissao);
		JtxtDataNascimento.addFocusListener(this);
		
		cons.gridx = 1;cons.gridy = 8;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblComissao,cons);
		cons.gridx = 2;cons.gridy = 8;cons.gridwidth = 1;cons.ipadx = 70;
		txtComissao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(txtComissao,cons);txtComissao.setNextFocusableComponent(txtDataCadastro);
		txtComissao.addFocusListener(this);

		cons.gridx = 6;cons.gridy = 8;cons.gridwidth = 1;cons.ipadx = 20;
//		lblDatacadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblDatacadastro,cons);
		cons.gridx = 7;cons.gridy = 8;cons.gridwidth = 2;cons.ipadx = 110;
		txtDataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(txtDataCadastro,cons);txtDataCadastro.setNextFocusableComponent(JtxtCep);
		txtDataCadastro.addFocusListener(this);

		/*
		 * INFORMAÇÕES DE LOCALIZAÇÃO DO MOTORISTA
		 */
		cons.gridx = 1;cons.gridy = 9;cons.gridwidth = 4;cons.ipadx = 70;
		lblInfoEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblInfoEndereco.setForeground(Color.BLUE);
		CadSer.add(lblInfoEndereco,cons);
		cons.gridx = 1;cons.gridy = 10;cons.gridwidth = 10;cons.ipadx = 550;
		CadSer.add(jsInfoEndereco,cons);

//		cons.fill = GridBagConstraints.HORIZONTAL;
		cons.gridx = 1;cons.gridy = 11;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblCep,cons);
//		lblCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		cons.gridx = 2;cons.gridy = 11;cons.gridwidth = 2;cons.ipadx = 80;
		JtxtCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtCep,cons);JtxtCep.setNextFocusableComponent(txtEndereco);
		JtxtCep.addFocusListener(this);

		cons.gridx = 1;cons.gridy = 12;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblEndereco,cons);
		cons.gridx = 2;cons.gridy = 12;cons.gridwidth = 9;cons.ipadx = 450;
		CadSer.add(txtEndereco,cons);txtEndereco.setNextFocusableComponent(txtNumero);
		txtEndereco.addFocusListener(this);

		cons.gridx = 1;cons.gridy = 13;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblNumero,cons);
		cons.gridx = 2;cons.gridy = 13;cons.gridwidth = 1;cons.ipadx = 50;
		CadSer.add(txtNumero,cons);txtNumero.setNextFocusableComponent(txtBairro);
		txtNumero.addFocusListener(this);
		
		cons.gridx = 4;cons.gridy = 13;cons.gridwidth = 1;cons.ipadx = 10;
		CadSer.add(lblBairro,cons);
		cons.gridx = 5;cons.gridy = 13;cons.gridwidth = 3;cons.ipadx = 300;
		CadSer.add(txtBairro,cons);txtBairro.setNextFocusableComponent(txtCidade);
		txtBairro.addFocusListener(this);

		cons.gridx = 1;cons.gridy = 14;cons.gridwidth = 1;cons.ipadx = 30;
//		lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblCidade,cons);
		cons.gridx = 2;cons.gridy = 14;cons.gridwidth = 2;cons.ipadx = 110;
		CadSer.add(txtCidade,cons);txtCidade.setNextFocusableComponent(jcbTipoEstado);
		txtCidade.addFocusListener(this);

		cons.gridx = 6;cons.gridy = 14;cons.gridwidth = 1;cons.ipadx = 10;
		CadSer.add(lblEstado,cons);
		cons.gridx = 7;cons.gridy = 14;cons.gridwidth = 1;cons.ipadx = 75;
//		txtEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		CadSer.add(jcbTipoEstado,cons);txtEstado.setNextFocusableComponent(JtxtTelefone);
		txtEstado.addFocusListener(this);

		/*
		 * INFORMAÇÕES PARA CONTACTAR O MOTORISTA POR TELEFONE
		 */
		cons.gridx = 1;cons.gridy = 15;cons.gridwidth = 4;cons.ipadx = 70;
		lblInfoContato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblInfoContato.setForeground(Color.BLUE);
		CadSer.add(lblInfoContato,cons);
		cons.gridx = 1;cons.gridy = 16;cons.gridwidth = 10;cons.ipadx = 550;
		CadSer.add(jsInfoContato,cons);
		
		cons.gridx = 1;cons.gridy = 17;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblTelefone,cons);
		cons.gridx = 2;cons.gridy = 17;cons.gridwidth = 2;cons.ipadx = 110;
		JtxtTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtTelefone,cons);JtxtTelefone.setNextFocusableComponent(JtxtCelular);
		JtxtTelefone.addFocusListener(this);

		cons.gridx = 6;cons.gridy = 17;cons.gridwidth = 1;cons.ipadx = 20;
//		lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblCelular,cons);
		cons.gridx = 7;cons.gridy = 17;cons.gridwidth = 2;cons.ipadx = 110;
		JtxtCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(JtxtCelular,cons);JtxtCelular.setNextFocusableComponent(jcbTipoBanco);
		JtxtCelular.addFocusListener(this);
		
		/*
		 * INFORMAÇÕES BANCÁRIAS DO MOTORISTA
		 */
		cons.gridx = 1;cons.gridy = 18;cons.gridwidth = 3;cons.ipadx = 70;
		lblInfoBanco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblInfoBanco.setForeground(Color.BLUE);
		CadSer.add(lblInfoBanco,cons);
		cons.gridx = 1;cons.gridy = 19;cons.gridwidth = 10;cons.ipadx = 550;
		CadSer.add(jsInfoBanco,cons);

		cons.gridx = 1;cons.gridy = 20;cons.gridwidth = 1;cons.ipadx = 30;
		CadSer.add(lblBanco,cons);
		cons.gridx = 2;cons.gridy = 20;cons.gridwidth = 3;cons.ipadx = 25;
		CadSer.add(jcbTipoBanco,cons);txtBanco.setNextFocusableComponent(jcbTipoConta);
		//txtBanco.addFocusListener(this);
		
		cons.gridx = 6;cons.gridy = 20;cons.gridwidth = 1;cons.ipadx = 20;
//		lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblTipo,cons);
		cons.gridx = 7;cons.gridy = 20;cons.gridwidth = 2;cons.ipadx = 30;cons.ipady = 1;
		CadSer.add(jcbTipoConta,cons);txtTipo.setNextFocusableComponent(txtAgencia);
		//txtTipo.addFocusListener(this);

		cons.gridx = 1;cons.gridy = 21;	cons.gridwidth = 1;cons.ipadx = 30;
//		lblAgencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(lblAgencia,cons);
		cons.gridx = 2;cons.gridy = 21;cons.gridwidth = 1;cons.ipadx = 110;
		txtAgencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(txtAgencia,cons);txtAgencia.setNextFocusableComponent(txtConta);
		txtAgencia.addFocusListener(this);

		cons.gridx = 6;cons.gridy = 21;cons.gridwidth = 1;cons.ipadx = 20;
		CadSer.add(lblConta,cons);
		cons.gridx = 7;cons.gridy = 21;cons.gridwidth = 3;cons.ipadx = 110;
		txtConta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		CadSer.add(txtConta,cons);//txtConta.setNextFocusableComponent(txtTipo);
		txtConta.addFocusListener(this);

		

		

//		cons.gridx = 4;cons.gridy = 14;cons.gridwidth = 1;cons.ipadx = 10;
//		lblDatacadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
//		CadSer.add(lblDatacadastro,cons);
//		cons.gridx = 5;cons.gridy = 14;cons.gridwidth = 2;cons.ipadx = 20;
//		JtxtDatacadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
//		CadSer.add(jXDPDataCadastro,cons);
//		jXDPDataCadastro.addFocusListener(this);

		cons.anchor = GridBagConstraints.EAST; cons.fill = GridBagConstraints.BOTH;
		cons.gridx = 20;cons.gridy = 3;cons.gridwidth = 1;cons.ipadx = 40;
		CadSer.add(btoIncluir,cons);btoIncluir.setNextFocusableComponent(btoLocalizar);
		btoIncluir.addActionListener(this);

		cons.gridx = 20;cons.gridy = 4;cons.gridwidth = 1;cons.ipadx = 40;
		CadSer.add(btoLocalizar,cons);btoLocalizar.setNextFocusableComponent(btoSair);
		btoLocalizar.addActionListener(this);

		cons.gridx = 20;cons.gridy = 4;cons.gridwidth = 1;cons.ipadx = 40;
		CadSer.add(btoAtualizar,cons);btoAtualizar.setNextFocusableComponent(btoExcluir);
		btoAtualizar.addActionListener(this);

		cons.gridx = 20;cons.gridy = 5;cons.gridwidth = 1;cons.ipadx = 40;
		CadSer.add(btoGravar,cons);btoGravar.setNextFocusableComponent(btoCancelar);
		btoGravar.addActionListener(this);

		cons.gridx = 20;cons.gridy = 6;cons.gridwidth = 1;cons.ipadx = 40;
		CadSer.add(btoExcluir,cons);btoExcluir.setNextFocusableComponent(btoCancelar);
		btoExcluir.addActionListener(this);

		cons.gridx = 20;cons.gridy = 21;cons.gridwidth = 1;cons.ipadx = 40;
		CadSer.add(btoSair,cons);btoSair.setNextFocusableComponent(txtCodigo);
		btoSair.addActionListener(this);

		cons.gridx = 20;cons.gridy = 21;cons.gridwidth = 1;cons.ipadx = 40;
		CadSer.add(btoCancelar,cons);
		btoCancelar.addActionListener(this);

		btoIncluir.setEnabled(true);
		btoLocalizar.setEnabled(true);
		btoAtualizar.setEnabled(false);
		btoGravar.setEnabled(false);
		btoExcluir.setEnabled(false);
		btoSair.setEnabled(true);
		btoCancelar.setVisible(false);

		}

	private MaskFormatter setMascara(String mascara){
		MaskFormatter mask = null;
		try{
			mask = new MaskFormatter(mascara);
		}catch(java.text.ParseException e){}
		return mask;
	}
	
	class MeuDocument extends PlainDocument{
		public void insertString(int offs, String str, AttributeSet a)throws BadLocationException{
			super.insertString(offs, str.toUpperCase(),a);
		}
	}
	
	public boolean validaCodigo( boolean isValid){
		if(!txtCodigo.getText().isEmpty()){
			try{
				txtCodigo.selectAll();
				Pattern pattern = Pattern.compile("[A-Z]{3,3}[ ][0-9]{4,4}");
				Matcher matcher = pattern.matcher(txtCodigo.getText());
				isValid = matcher.matches();
				return isValid;
			}catch(PatternSyntaxException pse){
				pse.printStackTrace();
			}
		}return isValid;
	}

	@Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void focusGained(FocusEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void focusLost(FocusEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void keyPressed(KeyEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void keyReleased(KeyEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void keyTyped(KeyEvent arg0) {
		// TODO Auto-generated method stub
		
	}
}