/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.cs.controlmoto.controller;

import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import br.com.cs.controlmoto.domain.CadTabelaPrecoDAO;
import br.com.cs.controlmoto.utils.ConvertStringToDate;
import br.com.cs.controlmoto.utils.FormataValor;
import br.com.cs.controlmoto.vo.CadTabelaPrecoVO;
import br.com.cs.controlmoto.vo.CadUsuariosVO;

/**
 * @company Fictec Cons. Inf.
 * @author {Clovis Silverio}
 * @since 09/05/2013
 * @version 1.0.0
 */
public class CadTabelaPreco extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form CadTabelaPreco
     */
    public CadTabelaPreco(String titulo, ControlMoto controlMoto) {
        initComponents(titulo, controlMoto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String titulo, ControlMoto controlMoto) {
    	
		/*
		 * Determina o caminho e o tipo de separador para os arquivos conforme o sistema operacional
		 */
		caminho = new File("").getAbsolutePath();
		separadorPath = System.getProperty("file.separator");

        jpInferior = new javax.swing.JPanel(); jpSuperior = new javax.swing.JPanel(); jbBotoes = new javax.swing.JPanel();
        
        jcbTabPreco = new javax.swing.JComboBox(); jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(); jToolBar1 = new javax.swing.JToolBar();
        
        btoNovo = new javax.swing.JButton(); btoNovo.setMnemonic(KeyEvent.VK_I); btoNovo.setToolTipText("Novo");
        btoNovo.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"hd_folha_novo_16x16.png"));
        
        btoSalvar = new javax.swing.JButton(); btoSalvar.setMnemonic(KeyEvent.VK_G); btoSalvar.setToolTipText("Gravar");
        btoSalvar.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"hd_flopy_16x16.png"));
        btoSalvar.setEnabled(false);
        
        btoLocalizar = new javax.swing.JButton();
        
        btoAtualizar = new javax.swing.JButton(); btoAtualizar.setMnemonic(KeyEvent.VK_A); btoAtualizar.setToolTipText("Atualizar");
		btoAtualizar.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"hd_atualiza_16x16.png"));
		btoAtualizar.setEnabled(false);
		
        btoCancelar = new javax.swing.JButton(); btoCancelar.setMnemonic(KeyEvent.VK_C); btoCancelar.setToolTipText("Cancelar");
		btoCancelar.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"hd_cancela_16x16.png"));
		btoCancelar.setEnabled(false);
		
        //btoExcluir = new javax.swing.JButton();
        
		btoImprimir = new javax.swing.JButton(); 
		
		btoSair = new javax.swing.JButton(); btoSair.setMnemonic(KeyEvent.VK_S); btoSair.setToolTipText("Sair");
		btoSair.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"cancelar_circular_16x16.png"));
        
        lblCodigo = new javax.swing.JLabel(); lblValorCodigo = new javax.swing.JLabel(); lblCodTabPreco = new javax.swing.JLabel();
        lblSequencia = new javax.swing.JLabel(); lblDescItemTabPreco = new javax.swing.JLabel(); lblDescricaoTabela = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel(); lblDataVigencia = new javax.swing.JLabel(); lblTabPrecoBusca = new javax.swing.JLabel();
        
        txtCodTabela = new javax.swing.JTextField(); txtDescTabPreco = new javax.swing.JTextField(); txtSequencia = new javax.swing.JTextField(); 
        txtDescItemTabPreco = new javax.swing.JTextField();
        
        jftPreco = new javax.swing.JFormattedTextField(); jftDataVigencia = new javax.swing.JFormattedTextField();
        
        jcbxTodos = new JCheckBox("Todos"); jcbxTodos.setHorizontalAlignment(SwingConstants.RIGHT);
        
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
        this.telaControlMoto = telaControlMoto;
    	controlMoto.jDesktopPane.add(this);

        setClosable(true);
        setIconifiable(true);
        setTitle("Tabela de Preço");
        setToolTipText("Tabela de Preço");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(300, 280));
        setPreferredSize(new java.awt.Dimension(610, 470));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            	formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        
        jpInferior.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        lblTabPrecoBusca.setText("Tabela Preço");

        jcbTabPreco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTabPrecoItemStateChanged(evt);
            }
        });
        jcbTabPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTabPrecoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Tabela", "Sequência", "Descrição Item", "Preço", "Vigência"
            }
        )
//        {
//            boolean[] canEdit = new boolean [] {
//                false, false, false, true, true
//            };
//            public boolean isCellEditable(int rowIndex, int columnIndex) {
//                return false;//canEdit [columnIndex];
//            }
//        }
        );
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpInferiorLayout = new javax.swing.GroupLayout(jpInferior);
        jpInferior.setLayout(jpInferiorLayout);
        jpInferiorLayout.setHorizontalGroup(
            jpInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(jpInferiorLayout.createSequentialGroup()
                        .addComponent(lblTabPrecoBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTabPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btoLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbxTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btoImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpInferiorLayout.setVerticalGroup(
            jpInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInferiorLayout.createSequentialGroup()
                .addGroup(jpInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTabPrecoBusca)
                    .addComponent(jcbTabPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpInferior, java.awt.BorderLayout.CENTER);

        jpSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setToolTipText("Barra de ferramentas");

        //btoNovo.setText("Novo");
        btoNovo.setFocusable(false);
        btoNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btoNovo);
        
        //btoSalvar.setText("Salvar");
        btoSalvar.setFocusable(false);
        btoSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btoSalvar);

        btoLocalizar.setText("Localizar");
        btoLocalizar.setFocusable(false);
        btoLocalizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoLocalizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoLocalizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btoLocalizar);

        //btoAtualizar.setText("Atualizar");
        btoAtualizar.setFocusable(false);
        btoAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btoAtualizar);

        //btoCancelar.setText("Cancelar");
        btoCancelar.setFocusable(false);
        btoCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btoCancelar);

//        btoExcluir.setText("Excluir");
//        btoExcluir.setFocusable(false);
//        btoExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        btoExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        btoExcluir.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btoExcluirActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(btoExcluir);

        btoImprimir.setText("Imprimir");
        btoImprimir.setFocusable(false);
        btoImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btoImprimir);

        //btoSair.setText("Sair");
        btoSair.setFocusable(false);
        btoSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btoSair);

        javax.swing.GroupLayout jbBotoesLayout = new javax.swing.GroupLayout(jbBotoes);
        jbBotoes.setLayout(jbBotoesLayout);
        jbBotoesLayout.setHorizontalGroup(
            jbBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jbBotoesLayout.setVerticalGroup(
            jbBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        lblCodigo.setText("Código");

        lblValorCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));
        lblValorCodigo.setMaximumSize(new java.awt.Dimension(100, 20));
        lblValorCodigo.setMinimumSize(new java.awt.Dimension(100, 20));
        lblValorCodigo.setPreferredSize(new java.awt.Dimension(100, 20));

        lblCodTabPreco.setText("Código Tablea");

        txtCodTabela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblDescricaoTabela.setText("Descrição Tabela");

        lblSequencia.setText("Sequência");

        txtSequencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblDescItemTabPreco.setText("Descrição Item");

        lblPreco.setText("Preço");

        jftPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jftPreco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblDataVigencia.setText("Data Vigência");

        try {
            jftDataVigencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataVigencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jpSuperiorLayout = new javax.swing.GroupLayout(jpSuperior);
        jpSuperior.setLayout(jpSuperiorLayout);
        jpSuperiorLayout.setHorizontalGroup(
            jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpSuperiorLayout.createSequentialGroup()
                        .addComponent(lblDataVigencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftDataVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSuperiorLayout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSuperiorLayout.createSequentialGroup()
                        .addComponent(lblSequencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSuperiorLayout.createSequentialGroup()
                        .addComponent(lblDescItemTabPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescItemTabPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSuperiorLayout.createSequentialGroup()
                        .addComponent(lblCodTabPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescricaoTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescTabPreco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpSuperiorLayout.setVerticalGroup(
            jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSuperiorLayout.createSequentialGroup()
                .addComponent(jbBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodTabPreco)
                    .addComponent(txtCodTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricaoTabela)
                    .addComponent(txtDescTabPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSequencia)
                    .addComponent(txtSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescItemTabPreco)
                    .addComponent(txtDescItemTabPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco))
                .addGap(18, 18, 18)
                .addGroup(jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataVigencia)
                    .addComponent(jftDataVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpSuperior, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    	CadTabelaPrecoVO cadTabelaPrecoVO = new CadTabelaPrecoVO(); List<CadTabelaPrecoVO> cadTbPrecoVOs = new ArrayList<>();
    	
    		try {
				cadTbPrecoVOs = new CadTabelaPrecoDAO().localizarAllTabPrecoByCombo();
				jcbTabPreco.addItem(null);
	    		for(CadTabelaPrecoVO cadTbPreco : cadTbPrecoVOs){
	    			jcbTabPreco.addItem(cadTbPreco.getCodigoTabela());
	    		}
			} catch (IllegalAccessException | InstantiationException | SQLException e) {
				e.printStackTrace();
			}
        
    }//GEN-LAST:event_formInternalFrameActivated
    
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
    	jcbTabPreco.removeAllItems();
    }//GEN-LAST:event_formInternalFrameClosing    

    private void btoImprimirActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btoNovoActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	CadTabelaPrecoVO cadTabelaPrecoVO = new CadTabelaPrecoVO();
    	try {
    		cadTabelaPrecoVO =  new CadTabelaPrecoDAO().getNovoTabPreco();
    		lblValorCodigo.setText( String.valueOf( cadTabelaPrecoVO.getIdTabelaPreco()  ));
    		
    		btoNovo.setEnabled(false); btoSalvar.setEnabled(true); btoAtualizar.setEnabled(false); btoCancelar.setEnabled(false);
    		btoSair.setEnabled(true);
		} catch (IllegalAccessException | InstantiationException | SQLException e) {
			e.printStackTrace();
		}
    }                                       

    private void btoSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	CadTabelaPrecoVO cadTabelaPrecoVO = new CadTabelaPrecoVO();
    	try {
    		cadTabelaPrecoVO.setIdTabelaPreco( Integer.valueOf( lblValorCodigo.getText() ) );
	        cadTabelaPrecoVO.setCodigoTabela( txtCodTabela.getText() );
	        cadTabelaPrecoVO.setDescricaoTabPreco( txtDescTabPreco.getText() ); 
	        cadTabelaPrecoVO.setSequencia( Integer.valueOf( txtSequencia.getText() ) );
	        cadTabelaPrecoVO.setDescricaoItem( txtDescItemTabPreco.getText() );
	        cadTabelaPrecoVO.setPreco( Double.valueOf( jftPreco.getText().replace(",", ".") ) );
			cadTabelaPrecoVO.setDataCriacao(new ConvertStringToDate().convertStringToDates( jftDataVigencia.getText() ) );
	        cadTabelaPrecoVO.setSituacao("Vigente");
	       
    		new CadTabelaPrecoDAO().salvarTabPreco(cadTabelaPrecoVO);
    	
		} catch (IllegalAccessException | InstantiationException | SQLException | ParseException e) {
			e.printStackTrace();
		}
    }                                       
    
    private void btoLocalizarActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	CadTabelaPrecoVO cadTabelaPrecoVO = null; List<CadTabelaPrecoVO> cadTbPrecoVOs = new ArrayList<>();
    	
    	FormataValor fv = new FormataValor();
    	
    	DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer(), centralizado = new DefaultTableCellRenderer(),
    	direita = new DefaultTableCellRenderer();  
  
        esquerda.setHorizontalAlignment(SwingConstants.LEFT); centralizado.setHorizontalAlignment(SwingConstants.CENTER);  
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        
    	try {
    		cadTabelaPrecoVO = new CadTabelaPrecoVO();
        	cadTabelaPrecoVO.setCodigoTabela(jcbTabPreco.getSelectedItem().toString());
        	
			cadTbPrecoVOs = new CadTabelaPrecoDAO().localizarTabPrecoByCodigo(cadTabelaPrecoVO);
			
			modelo = (DefaultTableModel) this.jTable1.getModel();
			modelo.setNumRows(0);
			
			for(CadTabelaPrecoVO cadTbPrecoVO : cadTbPrecoVOs){
				modelo.addRow(new String[]{ cadTbPrecoVO.getCodigoTabela(), String.valueOf(cadTbPrecoVO.getSequencia()), cadTbPrecoVO.getDescricaoItem(), String.valueOf(fv.formatValor(cadTbPrecoVO.getPreco().toString())), String.valueOf(new SimpleDateFormat("dd/MM/yyyy").format(cadTbPrecoVO.getDataCriacao())) } );
			}
			
            jTable1.getColumnModel().getColumn(0).setCellRenderer(esquerda);  
            jTable1.getColumnModel().getColumn(1).setCellRenderer(direita);  
            jTable1.getColumnModel().getColumn(2).setCellRenderer(esquerda);
            jTable1.getColumnModel().getColumn(3).setCellRenderer(direita);
            jTable1.getColumnModel().getColumn(4).setCellRenderer(direita);
			
			jTable1.setModel(modelo);
			
		} catch (IllegalAccessException | InstantiationException | SQLException e) {
			e.printStackTrace();
		}
    }                                            

    private void btoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {
    	
        CadTabelaPrecoVO cadTabelaPrecoVO = new CadTabelaPrecoVO();
        try {
	        cadTabelaPrecoVO.setIdTabelaPreco( Integer.valueOf( lblValorCodigo.getText() ) );
	        cadTabelaPrecoVO.setCodigoTabela( txtCodTabela.getText() );
	        cadTabelaPrecoVO.setDescricaoTabPreco( txtDescTabPreco.getText() ); 
	        cadTabelaPrecoVO.setSequencia( Integer.valueOf( txtSequencia.getText() ) );
	        cadTabelaPrecoVO.setDescricaoItem( txtDescItemTabPreco.getText() );
	        cadTabelaPrecoVO.setPreco( Double.valueOf( jftPreco.getText().replace(",", ".") ) );
	        cadTabelaPrecoVO.setDataCriacao(new ConvertStringToDate().convertStringToDates( jftDataVigencia.getText() ) );
	        
			new CadTabelaPrecoDAO().atualizarTabPrecoByCodigoAndSequencia(cadTabelaPrecoVO);
			if( !jcbTabPreco.getSelectedItem().toString().isEmpty() )
				btoLocalizar.doClick();
			
		} catch (ParseException | IllegalAccessException | InstantiationException | SQLException e) {
			e.printStackTrace();
		}

    }                                            

    private void btoCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CadTabelaPrecoVO cadTabelaPrecoVO = new CadTabelaPrecoVO();
        CadUsuariosVO usuariosVO = new CadUsuariosVO();
        try {
	        cadTabelaPrecoVO.setIdTabelaPreco( Integer.valueOf( lblValorCodigo.getText() ) );

	        cadTabelaPrecoVO.setDataAlteracao(new ConvertStringToDate().convertStringToDates(new SimpleDateFormat("dd/MM/yyyy").format( new java.util.Date())));
	        cadTabelaPrecoVO.setUsuarioAlteracaoFk(usuariosVO.getUsuarioPK());
	        
			new CadTabelaPrecoDAO().cancelarTabPrecoByCodigoAndSequencia(cadTabelaPrecoVO);
			
			if( !jcbTabPreco.getSelectedItem().toString().isEmpty() )
				btoLocalizar.doClick();
			
		} catch (ParseException | IllegalAccessException | InstantiationException | SQLException e) {
			e.printStackTrace();
		}
    }                                           

//    private void btoExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // TODO add your handling code here:
//    }                                          

    private void btoSairActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	System.exit(0);
    }                                       

    private void jcbTabPrecoActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        List<CadTabelaPrecoVO> cadTabelaPrecoVOs = new ArrayList<>(); 
//        CadTabelaPrecoVO cadTabelaPrecoVO = new CadTabelaPrecoVO();
//        cadTabelaPrecoVO.setCodigoTabela(txtCodTabela.getText());
//        try {
//			cadTabelaPrecoVOs = new CadTabelaPrecoDAO().localizarTabPrecoByCodigo(cadTabelaPrecoVO);
//
//			modelo = (DefaultTableModel) this.jTable1.getModel();
//			modelo.setNumRows(0);
//			
//			for(CadTabelaPrecoVO cadTbPrecoVO : cadTabelaPrecoVOs){
//				modelo.addRow(new String[]{ cadTbPrecoVO.getCodigoTabela(), String.valueOf(cadTbPrecoVO.getSequencia()), cadTbPrecoVO.getDescricaoItem(), String.valueOf(cadTbPrecoVO.getPreco()), String.valueOf(cadTbPrecoVO.getDataCriacao()) } );
//			}
//			
//			jTable1.setModel(modelo);
//			
//		} catch (IllegalAccessException | InstantiationException | SQLException e) {
//			e.printStackTrace();
//		}
        
    }                                           

    private void jcbTabPrecoItemStateChanged(java.awt.event.ItemEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
    	FormataValor fv = new FormataValor();
        int linha = jTable1.getSelectedRow();
        CadTabelaPrecoVO cadTabelaPrecoVO = new CadTabelaPrecoVO();
        cadTabelaPrecoVO.setCodigoTabela(jTable1.getValueAt(linha, 0).toString());
        cadTabelaPrecoVO.setSequencia(Integer.valueOf(jTable1.getValueAt(linha, 1).toString()));
        
        try {
			cadTabelaPrecoVO = new CadTabelaPrecoDAO().localizarTabPrecoByCodigoAndSequencia(cadTabelaPrecoVO);
			
			lblValorCodigo.setText(cadTabelaPrecoVO.getIdTabelaPreco().toString());
			txtCodTabela.setText(cadTabelaPrecoVO.getCodigoTabela()); //txtCodTabela.setEnabled(false);
			txtDescTabPreco.setText(cadTabelaPrecoVO.getDescricaoTabPreco()); 
			txtSequencia.setText(cadTabelaPrecoVO.getSequencia().toString()); //txtSequencia.setEnabled(false);
			txtDescItemTabPreco.setText(cadTabelaPrecoVO.getDescricaoItem());
			jftPreco.setText(fv.formatValor(cadTabelaPrecoVO.getPreco().toString()));
			jftDataVigencia.setText(new SimpleDateFormat("dd/MM/yyyy").format(cadTabelaPrecoVO.getDataCriacao()));
			
			btoNovo.setEnabled(false); btoSalvar.setEnabled(false); btoAtualizar.setEnabled(true); btoCancelar.setEnabled(true);
			btoSair.setEnabled(true);
			
		} catch (IllegalAccessException | InstantiationException | SQLException e) {
			e.printStackTrace();
		}
    }                                    

    private ControlMoto telaControlMoto;
    
    static int openFrameCount = 4;
    static final int xOffset = 4, yOffset = 4;
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btoAtualizar, btoSalvar, btoCancelar, btoImprimir, btoLocalizar, btoNovo, btoSair;//btoExcluir, 
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jbBotoes;
    private javax.swing.JComboBox jcbTabPreco;
    private javax.swing.JFormattedTextField jftDataVigencia, jftPreco;
    private javax.swing.JPanel jpInferior, jpSuperior;
    private javax.swing.JLabel lblCodTabPreco, lblCodigo, lblDataVigencia, lblDescItemTabPreco, lblDescricaoTabela, lblPreco,
    lblSequencia, lblTabPrecoBusca, lblValorCodigo;
    private javax.swing.JTextField txtCodTabela, txtDescItemTabPreco, txtDescTabPreco, txtSequencia;
    private DefaultTableModel modelo;
    private javax.swing.JCheckBox jcbxTodos;
    private java.lang.String caminho, separadorPath;
    // End of variables declaration                   
}
