package br.com.cs.controlmoto.controller;


import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.SwingConstants;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import br.com.cs.controlmoto.domain.CadTarefaDAO;
import br.com.cs.controlmoto.vo.CadTarefaVO;

/**
 * @company Fictec Cons. Inf.
 * @author {Clovis Silverio}
 * @version 1.0.1
 * @since 30/03/2013
 */
public class CadTarefa extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
    /**
     * Creates new form CadTarefa
     */
    public CadTarefa(String titulo, ControlMoto controlMoto) {
        initComponents(titulo, controlMoto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param telaControlMoto 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String titulo, ControlMoto controlMoto) {

        jpCampos = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblVlCodTarefa = new javax.swing.JLabel();
        lblDescricaoTarefa = new javax.swing.JLabel();
        txtDescricaoTarefa = new javax.swing.JTextField();
        jrbAtivo = new javax.swing.JRadioButton();
        jpBotoes = new javax.swing.JPanel();
        btoAtualizar = new javax.swing.JButton(); btoAtualizar.setPreferredSize(new Dimension(30,30));
        btoIncluir = new javax.swing.JButton(); btoIncluir.setPreferredSize(new Dimension(30,30));
        btoSalvar = new javax.swing.JButton(); btoSalvar.setPreferredSize(new Dimension(30,30));
        jpGrid = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
        this.telaControlMoto = telaControlMoto;
    	controlMoto.jDesktopPane.add(this);
    	
    	setVisible(true);
        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Tarefas");
        setToolTipText("Cadastrar Tarefas");
        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(470, 300));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
			@Override
			public void internalFrameActivated(InternalFrameEvent evt) {
				formInternalFrameActivated(evt);
			}
			@Override
			public void internalFrameClosed(InternalFrameEvent evt) {
				// TODO Auto-generated method stub	
			}
			@Override
			public void internalFrameClosing(InternalFrameEvent evt) {
				// TODO Auto-generated method stub	
			}
			@Override
			public void internalFrameDeactivated(InternalFrameEvent evt) {
				// TODO Auto-generated method stub
			}
			@Override
			public void internalFrameDeiconified(InternalFrameEvent evt) {
				// TODO Auto-generated method stub	
			}
			@Override
			public void internalFrameIconified(InternalFrameEvent evt) {
				// TODO Auto-generated method stub	
			}
			@Override
			public void internalFrameOpened(InternalFrameEvent evt) {
				// TODO Auto-generated method stub	
			}
        });
                
        lblCodigo.setText("Código");

        lblVlCodTarefa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVlCodTarefa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblVlCodTarefa.setMaximumSize(new java.awt.Dimension(36, 20));
        lblVlCodTarefa.setPreferredSize(new java.awt.Dimension(36, 20));

        lblDescricaoTarefa.setText("Descrição");

        jrbAtivo.setSelected(true);
        jrbAtivo.setText("Ativo");
        jrbAtivo.setToolTipText("Tarefas ativas");

        javax.swing.GroupLayout jpCamposLayout = new javax.swing.GroupLayout(jpCampos);
        jpCampos.setLayout(jpCamposLayout);
        jpCamposLayout.setHorizontalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoTarefa)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addComponent(lblVlCodTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbAtivo))
                    .addComponent(txtDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpCamposLayout.setVerticalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbAtivo)
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVlCodTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricaoTarefa))))
                .addGap(21, 21, 21))
        );

        btoAtualizar.setText("Atualizar");
        btoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoAtualizarActionPerformed(evt);
            }
        });

        btoIncluir.setText("Incluir");
        btoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoIncluirActionPerformed(evt);
            }
        });

        btoSalvar.setText("Salvar");
        btoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpBotoesLayout.createSequentialGroup()
                        .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btoIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btoAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btoIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btoAtualizar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jpGrid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tarefas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(20);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
        jTable1.getColumnModel().getColumn(1).setMinWidth(90);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(220);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(300);
        jTable1.getColumnModel().getColumn(2).setMinWidth(20);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(40);

        javax.swing.GroupLayout jpGridLayout = new javax.swing.GroupLayout(jpGrid);
        jpGrid.setLayout(jpGridLayout);
        jpGridLayout.setHorizontalGroup(
            jpGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGridLayout.setVerticalGroup(
            jpGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGridLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
               
        atualizaGrid();

        pack();
    }// </editor-fold>                        

	private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
        atualizaGrid();
        System.out.println("formInternalFrameActivated");
    }

	private void btoIncluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        CadTarefaVO cadTarefaVO = null; CadTarefaDAO cadTarefaDAO = null;
        try {
            cadTarefaVO = new CadTarefaVO(); cadTarefaDAO = new CadTarefaDAO();
            
            cadTarefaVO = cadTarefaDAO.controlaPkTarefa();
            String id = String.valueOf(cadTarefaVO.getCodigoTarefa());
            if(!id.isEmpty() && id != "null"){
                lblVlCodTarefa.setText(String.valueOf(cadTarefaVO.getCodigoTarefa()+1));
            }else{
                lblVlCodTarefa.setText(String.valueOf(1));
            }
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                cadTarefaDAO.closeTarefaConexao();
                btoIncluir.setEnabled(false);btoSalvar.setEnabled(true);btoAtualizar.setEnabled(false);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                          

    private void btoSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        CadTarefaVO cadTarefaVO = null; CadTarefaDAO cadTarefaDAO = null;
        try {
            cadTarefaVO = new CadTarefaVO(); cadTarefaDAO = new CadTarefaDAO();
            
            cadTarefaVO.setCodigoTarefa(Integer.valueOf(lblVlCodTarefa.getText()));
            cadTarefaVO.setDescricaoTarefa(txtDescricaoTarefa.getText());
            if(jrbAtivo.isSelected()){
                cadTarefaVO.setStatusTarefa("Sim");
            }else{
                cadTarefaVO.setStatusTarefa("Não");
            }
            cadTarefaDAO.salvaTarefa(cadTarefaVO);
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                cadTarefaDAO.closeTarefaConexao();
                limpaCampos();
                atualizaGrid();
                btoIncluir.setEnabled(true);btoSalvar.setEnabled(false);btoAtualizar.setEnabled(false);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                         

    private void btoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        CadTarefaVO cadTarefaVO = null; CadTarefaDAO cadTarefaDAO = null;
        try {
            cadTarefaVO = new CadTarefaVO(); cadTarefaDAO = new CadTarefaDAO();
            
            cadTarefaVO.setCodigoTarefa(Integer.valueOf(lblVlCodTarefa.getText()));
            cadTarefaVO.setDescricaoTarefa(txtDescricaoTarefa.getText());
            if(jrbAtivo.isSelected()){
                cadTarefaVO.setStatusTarefa("Sim");
            }else{
                cadTarefaVO.setStatusTarefa("Não");
            }
            cadTarefaDAO.atualizaTarefaByPk(cadTarefaVO);
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                cadTarefaDAO.closeTarefaConexao();
                limpaCampos();
                atualizaGrid();
                btoIncluir.setEnabled(true);btoSalvar.setEnabled(false);btoAtualizar.setEnabled(false);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                            

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        CadTarefaVO cadTarefaVO = null; CadTarefaDAO cadTarefaDAO=null;
        try {
            int linha = jTable1.getSelectedRow();
            
            cadTarefaVO = new CadTarefaVO(); cadTarefaDAO = new CadTarefaDAO();
            
            cadTarefaVO.setCodigoTarefa(Integer.valueOf(jTable1.getValueAt(linha, 0).toString()));

            cadTarefaVO = cadTarefaDAO.buscaTarefaByPk(cadTarefaVO);
            
            lblVlCodTarefa.setText(String.valueOf(cadTarefaVO.getCodigoTarefa()));
            txtDescricaoTarefa.setText(cadTarefaVO.getDescricaoTarefa());
            if("Sim".equals(cadTarefaVO.getStatusTarefa())){
                jrbAtivo.setSelected(true);
            }else{
                jrbAtivo.setSelected(false);            
            }      
        } catch ( SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                cadTarefaDAO.closeTarefaConexao();
                btoIncluir.setEnabled(false);btoSalvar.setEnabled(false);btoAtualizar.setEnabled(true);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasPagar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                    

    public void limpaCampos(){
        lblVlCodTarefa.setText("");
        txtDescricaoTarefa.setText("");
    }
    
    public void atualizaGrid(){
        CadTarefaVO cadTarefaVO = null; CadTarefaDAO cadTarefaDAO = null;
        List<CadTarefaVO> epdList = null;
        DefaultTableModel modelo; DefaultTableCellRenderer esquerda=null, direita=null, centro=null;
        try {
            esquerda = new DefaultTableCellRenderer(); direita = new DefaultTableCellRenderer(); centro = new DefaultTableCellRenderer();

            esquerda.setHorizontalAlignment(SwingConstants.LEFT); direita.setHorizontalAlignment(SwingConstants.RIGHT);
            centro.setHorizontalAlignment(SwingConstants.CENTER);
            
            epdList = new ArrayList<CadTarefaVO>();
            
            cadTarefaVO = new CadTarefaVO(); cadTarefaDAO = new CadTarefaDAO();
            
            epdList = cadTarefaDAO.listaTarefas(cadTarefaVO);
            
            modelo = (DefaultTableModel) this.jTable1.getModel();
            modelo.setNumRows(0);
            for(CadTarefaVO cTarefaVO : epdList){
               modelo.addRow(new String[]{ String.valueOf(cTarefaVO.getCodigoTarefa()), cTarefaVO.getDescricaoTarefa(), cTarefaVO.getStatusTarefa() });
            }
            
            jTable1.getColumnModel().getColumn(0).setCellRenderer(direita);
            jTable1.getColumnModel().getColumn(1).setCellRenderer(esquerda);
            jTable1.getColumnModel().getColumn(2).setCellRenderer(esquerda);
            //jTable1.getColumnModel().getColumn(3).setCellRenderer(centro);
            
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                cadTarefaDAO.closeTarefaConexao();
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(CadTarefa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    //
    private ControlMoto telaControlMoto;
    
    static int openFrameCount = 2;
    static final int xOffset = 10, yOffset = 65;
 
    // Variables declaration - do not modify                     
    private javax.swing.JButton btoAtualizar;
    private javax.swing.JButton btoIncluir;
    private javax.swing.JButton btoSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpCampos;
    private javax.swing.JPanel jpGrid;
    private javax.swing.JRadioButton jrbAtivo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricaoTarefa;
    private javax.swing.JLabel lblVlCodTarefa;
    private javax.swing.JTextField txtDescricaoTarefa;
    // End of variables declaration                   

}
