package br.com.cs.controlmoto.controller;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import br.com.cs.controlmoto.domain.ContasReceberDAO;
import br.com.cs.controlmoto.domain.DevedorDAO;
import br.com.cs.controlmoto.utils.ConvertStringToDate;
import br.com.cs.controlmoto.utils.FormataValor;
import br.com.cs.controlmoto.utils.ValidaData;
import br.com.cs.controlmoto.vo.ContasReceber1VO;
import br.com.cs.controlmoto.vo.ContasReceberVO;
import br.com.cs.controlmoto.vo.DevedorVO;
import br.com.cs.controlmoto.vo.EspecieDocumentoVO;
import br.com.cs.controlmoto.vo.FormaCobrancaJurosVO;
import br.com.cs.controlmoto.vo.FormaPagtoVO;
import br.com.cs.controlmoto.vo.SituacaoVO;
import br.com.cs.controlmoto.vo.TipoPagtoVO;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Company Fictec Cons. Inf.
 * @since 06/09/2012
 * @version 1.0.6
 * @author Clovis
 */
public class ContasReceber extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form ContasReceber
     */
    public ContasReceber(String titulo, ControlMoto controlmoto) {
        initComponents(titulo, controlmoto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String titulo, ControlMoto controlmoto) {

        jpCampos = new javax.swing.JPanel(); jpBotao = new javax.swing.JPanel(); jpLista = new javax.swing.JPanel();
       
        lblCod = new javax.swing.JLabel(); lblCodConta = new javax.swing.JLabel(); lblSituacao = new javax.swing.JLabel();
        lblCredor = new javax.swing.JLabel(); lblDevedorNome = new javax.swing.JLabel(); lblDtDocumento = new javax.swing.JLabel();
        lvlDtVencimento = new javax.swing.JLabel(); lblDtQuitacao = new javax.swing.JLabel(); lblNumDocumento = new javax.swing.JLabel(); 
        lblEspDocumento = new javax.swing.JLabel(); lblVlDocumento = new javax.swing.JLabel(); lblTpPagto = new javax.swing.JLabel(); 
        lblFormaPagto = new javax.swing.JLabel(); lblTxJuros = new javax.swing.JLabel(); lblTpFormaPagto = new javax.swing.JLabel(); 
        lblTxMulta = new javax.swing.JLabel(); lblFormaPagtoDescricao = new javax.swing.JLabel(); lblEspDocumentoDescicao = new javax.swing.JLabel();
        lblTpPagtoDescricao = new javax.swing.JLabel(); lblFormaCobrancaJurosDescricao = new javax.swing.JLabel(); lblVlPagar = new javax.swing.JLabel();
        lblCodBarras = new javax.swing.JLabel(); jLabel17 = new javax.swing.JLabel(); lblCodContaList = new javax.swing.JLabel(); 
        lblDtFinal = new javax.swing.JLabel(); lblCredorList = new javax.swing.JLabel(); 
        
        jrbTpTitulo = new javax.swing.JRadioButton(); jrbTpTaxaJuros = new javax.swing.JRadioButton(); jrbTpTaxaMulta = new javax.swing.JRadioButton();
        
        jcbSituacao = new javax.swing.JComboBox(); jcbEspDocumento = new javax.swing.JComboBox(); jcbTpPagto = new javax.swing.JComboBox();
        jcbFormaPagto = new javax.swing.JComboBox(); jcbTpFormaCobranca = new javax.swing.JComboBox(); jcbDevedor = new javax.swing.JComboBox();
        jcbDevedorList = new javax.swing.JComboBox();
        
        jftDtDocumento = new javax.swing.JFormattedTextField(); jftDtVencimento = new javax.swing.JFormattedTextField(); jftDtQuitacao = new javax.swing.JFormattedTextField();
        jftTaxaJuros = new javax.swing.JFormattedTextField(); jftVlDocumento = new javax.swing.JFormattedTextField(); jftTxMulta = new javax.swing.JFormattedTextField();
        jftDtInicio = new javax.swing.JFormattedTextField(); jftDtFinal = new javax.swing.JFormattedTextField(); 
        
        txtNumDocumento = new javax.swing.JTextField(); txtVlPagar = new javax.swing.JTextField(); txtCodBarra = new javax.swing.JTextField();
        txtCodContaList = new javax.swing.JTextField(); 
        
        btoIncluir = new javax.swing.JButton(); btoSalvar = new javax.swing.JButton(); btoAtualizar = new javax.swing.JButton();
        btoExcluir = new javax.swing.JButton(); btoLocalizar = new javax.swing.JButton();
        
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
        this.telaControlMoto = telaControlMoto;
    	controlmoto.jDesktopPane.add(this);

        setClosable(true);
        setIconifiable(true);
        setTitle("Contas a Receber");
        setToolTipText("Contas a Receber");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(900, 800));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(805, 570));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jpCampos.setMaximumSize(new java.awt.Dimension(500, 200));
        jpCampos.setMinimumSize(new java.awt.Dimension(300, 200));
        jpCampos.setPreferredSize(new java.awt.Dimension(450, 200));

        lblCod.setText("Código");

        jrbTpTitulo.setSelected(true);
        jrbTpTitulo.setText("Título");
        jrbTpTitulo.setToolTipText("Conta de concessionária (Telefone/Água/Luz) clique aqui.");

        lblCodConta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodConta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblCodConta.setMaximumSize(new java.awt.Dimension(34, 20));
        lblCodConta.setMinimumSize(new java.awt.Dimension(34, 20));
        lblCodConta.setPreferredSize(new java.awt.Dimension(34, 20));

        lblSituacao.setText("Situação");

        lblCredor.setText("Devedor");

        lblDevedorNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblDevedorNome.setMaximumSize(new java.awt.Dimension(34, 20));
        lblDevedorNome.setMinimumSize(new java.awt.Dimension(34, 20));
        lblDevedorNome.setPreferredSize(new java.awt.Dimension(34, 20));

        lblDtDocumento.setText("Data Documento");

        try {
            jftDtDocumento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDtDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftDtDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftDtDocumentoFocusLost(evt);
            }
        });

        lvlDtVencimento.setText("Data Vencimento");

        try {
            jftDtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDtVencimento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftDtVencimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftDtVencimentoFocusLost(evt);
            }
        });

        lblDtQuitacao.setText("Data Quitação");

        try {
            jftDtQuitacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDtQuitacao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftDtQuitacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftDtQuitacaoFocusLost(evt);
            }
        });

        lblNumDocumento.setText("Núm Documento");

        txtNumDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblEspDocumento.setText("Esp Documento");

        jcbEspDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEspDocumentoActionPerformed(evt);
            }
        });

        lblVlDocumento.setText("R$ Documento");

        lblTpPagto.setText("Tipo de Pagamento");

        jcbTpPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTpPagtoActionPerformed(evt);
            }
        });

        lblFormaPagto.setText("Forma de Pagamento");

        jcbFormaPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFormaPagtoActionPerformed(evt);
            }
        });

        lblTxJuros.setText("Taxa de Juros");

        lblTpFormaPagto.setText("Forma de Cobranca");

        jcbTpFormaCobranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTpFormaCobrancaActionPerformed(evt);
            }
        });

        jrbTpTaxaJuros.setSelected(true);
        jrbTpTaxaJuros.setText("Real / Percentual");
        jrbTpTaxaJuros.setToolTipText("Taxa de juros em percentual clique aqui.");

        lblTxMulta.setText("Taxa de Multa");

        jrbTpTaxaMulta.setSelected(true);
        jrbTpTaxaMulta.setText("Real / Percentual");
        jrbTpTaxaMulta.setToolTipText("Taxa de multa em percentual clique aqui.");
        jrbTpTaxaMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTpTaxaMultaActionPerformed(evt);
            }
        });

        lblFormaPagtoDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblFormaPagtoDescricao.setMaximumSize(new java.awt.Dimension(36, 20));
        lblFormaPagtoDescricao.setMinimumSize(new java.awt.Dimension(36, 20));
        lblFormaPagtoDescricao.setPreferredSize(new java.awt.Dimension(36, 20));

        lblEspDocumentoDescicao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblEspDocumentoDescicao.setMaximumSize(new java.awt.Dimension(36, 20));
        lblEspDocumentoDescicao.setMinimumSize(new java.awt.Dimension(36, 20));
        lblEspDocumentoDescicao.setPreferredSize(new java.awt.Dimension(36, 20));

        lblTpPagtoDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblTpPagtoDescricao.setMaximumSize(new java.awt.Dimension(36, 20));
        lblTpPagtoDescricao.setMinimumSize(new java.awt.Dimension(36, 20));
        lblTpPagtoDescricao.setPreferredSize(new java.awt.Dimension(36, 20));

        lblFormaCobrancaJurosDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblFormaCobrancaJurosDescricao.setMaximumSize(new java.awt.Dimension(36, 20));
        lblFormaCobrancaJurosDescricao.setMinimumSize(new java.awt.Dimension(36, 20));
        lblFormaCobrancaJurosDescricao.setPreferredSize(new java.awt.Dimension(36, 20));

        lblVlPagar.setText("Valor a Pagar");

        txtVlPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlPagar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVlPagarFocusGained(evt);
            }
        });

        lblCodBarras.setText("Código de Barras");

        txtCodBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBarraActionPerformed(evt);
            }
        });

        jftTaxaJuros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jftTaxaJuros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftTaxaJuros.setMaximumSize(new java.awt.Dimension(23, 23));

        jftVlDocumento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jftVlDocumento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftVlDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftVlDocumentoActionPerformed(evt);
            }
        });

        jftTxMulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jftTxMulta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jcbDevedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbDevedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDevedorActionPerformed(evt);
            }
        });

        jpBotao.setMaximumSize(new java.awt.Dimension(130, 200));
        jpBotao.setMinimumSize(new java.awt.Dimension(90, 200));
        jpBotao.setPreferredSize(new java.awt.Dimension(100, 200));

        btoIncluir.setText("Incluir");
        btoIncluir.setToolTipText("Incluir nova conta");
        btoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoIncluirActionPerformed(evt);
            }
        });

        btoSalvar.setText("Salvar");
        btoSalvar.setToolTipText("Salva a nova conta");
        btoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSalvarActionPerformed(evt);
            }
        });

        btoAtualizar.setText("Atualizar");
        btoAtualizar.setToolTipText("Atualiza uma conta");
        btoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoAtualizarActionPerformed(evt);
            }
        });

        btoExcluir.setText("Excluir");
        btoExcluir.setToolTipText("Exclui uma conta");
        btoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotaoLayout = new javax.swing.GroupLayout(jpBotao);
        jpBotao.setLayout(jpBotaoLayout);
        jpBotaoLayout.setHorizontalGroup(
            jpBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btoAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btoIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jpBotaoLayout.setVerticalGroup(
            jpBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btoIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btoAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btoExcluir)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCamposLayout = new javax.swing.GroupLayout(jpCampos);
        jpCampos.setLayout(jpCamposLayout);
        jpCamposLayout.setHorizontalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxJuros)
                            .addComponent(lblTxMulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftTaxaJuros, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jftTxMulta))
                        .addGap(13, 13, 13)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(lblTpFormaPagto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbTpFormaCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jrbTpTaxaMulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormaCobrancaJurosDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVlPagar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbTpTaxaJuros)
                            .addComponent(txtVlPagar)))
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addComponent(lblCodBarras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodBarra))
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCod)
                            .addComponent(lblCredor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodConta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(jrbTpTitulo)
                                .addGap(68, 68, 68)
                                .addComponent(lblSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDevedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addComponent(lblTpPagto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTpPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTpPagtoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFormaPagto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFormaPagtoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addComponent(lblNumDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEspDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbEspDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEspDocumentoDescicao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVlDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftVlDocumento))
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addComponent(lblDtDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftDtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lvlDtVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDtQuitacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftDtQuitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpCamposLayout.setVerticalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTpTitulo)
                    .addComponent(lblCodConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCod)
                    .addComponent(lblSituacao)
                    .addComponent(jcbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredor)
                    .addComponent(jcbDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDevedorNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftDtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtDocumento)
                    .addComponent(lvlDtVencimento)
                    .addComponent(jftDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtQuitacao)
                    .addComponent(jftDtQuitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumDocumento)
                    .addComponent(lblEspDocumento)
                    .addComponent(jcbEspDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVlDocumento)
                    .addComponent(lblEspDocumentoDescicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftVlDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTpPagtoDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTpPagto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbFormaPagto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTpPagto)
                        .addComponent(lblFormaPagto))
                    .addComponent(lblFormaPagtoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbTpTaxaJuros)
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTxJuros)
                        .addComponent(lblTpFormaPagto)
                        .addComponent(jcbTpFormaCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jftTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFormaCobrancaJurosDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxMulta)
                    .addComponent(jrbTpTaxaMulta)
                    .addComponent(lblVlPagar)
                    .addComponent(txtVlPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftTxMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodBarras)
                    .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addComponent(jpBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblCod.getAccessibleContext().setAccessibleName("lblCodigo");
        jrbTpTitulo.getAccessibleContext().setAccessibleName("jrbTítulo");
        lblCodConta.getAccessibleContext().setAccessibleName("lblCodConta");
        lblSituacao.getAccessibleContext().setAccessibleName("lblSituacao");
        jcbSituacao.getAccessibleContext().setAccessibleName("jcbSituacao");
        lblCredor.getAccessibleContext().setAccessibleName("lblCredor");
        lblDevedorNome.getAccessibleContext().setAccessibleName("lblDevedorNome");
        lblDtDocumento.getAccessibleContext().setAccessibleName("lblDtDocumento");
        jftDtDocumento.getAccessibleContext().setAccessibleName("jftDtDocumento");
        lvlDtVencimento.getAccessibleContext().setAccessibleName("lblDtVencimento");
        jftDtVencimento.getAccessibleContext().setAccessibleName("jftDtVencimento");
        lblDtQuitacao.getAccessibleContext().setAccessibleName("lblDtQuitacao");
        jftDtQuitacao.getAccessibleContext().setAccessibleName("jftDtQuitacao");
        lblNumDocumento.getAccessibleContext().setAccessibleName("lblNumDocumento");
        txtNumDocumento.getAccessibleContext().setAccessibleName("txtNumDocumento");
        lblEspDocumento.getAccessibleContext().setAccessibleName("lblEspDocumento");
        jcbEspDocumento.getAccessibleContext().setAccessibleName("jcbEspDocumento");
        lblVlDocumento.getAccessibleContext().setAccessibleName("lblVlDocumento");

        getContentPane().add(jpCampos, java.awt.BorderLayout.CENTER);

        jpLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualizacao das Contas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10), new java.awt.Color(0, 0, 102))); // NOI18N
        jpLista.setToolTipText("Visualizacao das Contas");

        jLabel17.setText("Data Início");

        try {
            jftDtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDtInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftDtInicio.setToolTipText("Data de Vencimento");
        jftDtInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftDtInicioFocusLost(evt);
            }
        });

        lblCodContaList.setText("Código da Conta");

        txtCodContaList.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblDtFinal.setText("Data Final");

        try {
            jftDtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDtFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftDtFinal.setToolTipText("Data de Vencimento");
        jftDtFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftDtFinalFocusLost(evt);
            }
        });

        lblCredorList.setText("Devedor");

        btoLocalizar.setText("Localizar");
        btoLocalizar.setToolTipText("Localiza contas");
        btoLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoLocalizarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Conta", "Devedor", "Data Documento", "Núm Documento", "Data Vencimento", "Valor a Pagar", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpListaLayout = new javax.swing.GroupLayout(jpLista);
        jpLista.setLayout(jpListaLayout);
        jpListaLayout.setHorizontalGroup(
            jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpListaLayout.createSequentialGroup()
                        .addGroup(jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpListaLayout.createSequentialGroup()
                                .addComponent(lblCodContaList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodContaList, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(lblDtFinal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpListaLayout.createSequentialGroup()
                                .addComponent(lblCredorList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbDevedorList, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btoLocalizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpListaLayout.setVerticalGroup(
            jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodContaList)
                    .addComponent(txtCodContaList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jftDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtFinal)
                    .addComponent(jftDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredorList)
                    .addComponent(jcbDevedorList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoLocalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jpLista, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbTpTaxaMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTpTaxaMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTpTaxaMultaActionPerformed

    private void btoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoIncluirActionPerformed
        btoIncluir.setEnabled(false);btoSalvar.setEnabled(true);btoAtualizar.setEnabled(false);btoExcluir.setEnabled(false);
        ContasReceberVO crVO; ContasReceberDAO crDao=null;
        try {
            crVO = new ContasReceberVO();
            crDao = new ContasReceberDAO();
            //Metodo que controla o id do cantas a pagar
            crVO = crDao.controlarContasReceberPk(crVO);
             String id = String.valueOf(crVO.getContasReceberPk());
             if(!id.isEmpty() && id != "null"){
                lblCodConta.setText(String.valueOf(crVO.getContasReceberPk()+1));
             }else{
                lblCodConta.setText(String.valueOf(1));
             }
            //Seta a combo situacao para iniciar um lancamento
            jcbSituacao.setSelectedItem("A vencer");
        } catch (ParseException ex) {
            Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                crDao.closeContasReceberDAO();
                //limpaCampos();
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btoIncluirActionPerformed

    private void jcbFormaPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFormaPagtoActionPerformed
        FormaPagtoVO fpVO = new FormaPagtoVO();
        int formaPg = (String.valueOf(jcbFormaPagto.getSelectedItem()).equals("null") ? 0 : Integer.valueOf(jcbFormaPagto.getSelectedItem().toString()) );
        fpVO.setCodForma(formaPg);
        if(jcbFormaPagto.getSelectedItem() == null ){//fpVO.getCodForma() == 0){// || String.valueOf(fpVO.getCodForma()) == "null" ){
            lblFormaPagtoDescricao.setText("");
        }else{
            ContasReceberDAO crDao = null;
            try {
                crDao = new ContasReceberDAO();
                fpVO = crDao.buscarDescricaoFormaPagtoByCodForma(fpVO);
                lblFormaPagtoDescricao.setText( fpVO.getDescricao() );
            } catch (ParseException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    crDao.closeContasReceberDAO();
                } catch ( SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jcbFormaPagtoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jcbEspDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEspDocumentoActionPerformed
        EspecieDocumentoVO edVO = new EspecieDocumentoVO();
        String codEspecDoc = String.valueOf(jcbEspDocumento.getSelectedItem());
        edVO.setCodEspDocumento(codEspecDoc);
        if(edVO.getCodEspDocumento() == "null"){
            lblEspDocumentoDescicao.setText("");
        }else{
            ContasReceberDAO crDao = null;
            try {
                crDao = new ContasReceberDAO();
                edVO = crDao.buscarEspecieDocumentoDescricaoByPk(edVO);
                lblEspDocumentoDescicao.setText( edVO.getDescricao() );
            } catch (ParseException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    crDao.closeContasReceberDAO();
                } catch ( SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jcbEspDocumentoActionPerformed

    private void jcbTpPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTpPagtoActionPerformed
        TipoPagtoVO tpVO = new TipoPagtoVO();
        String tpPagto = String.valueOf(jcbTpPagto.getSelectedItem());
        tpVO.setCodTpPagto(tpPagto);
        if(tpVO.getCodTpPagto()=="null"){
            lblTpPagtoDescricao.setText("");
        }else{
            ContasReceberDAO crDao = null;
            try {
                crDao = new ContasReceberDAO();
                tpVO = crDao.buscarTipoPagtoDescricaoByPk(tpVO);
                lblTpPagtoDescricao.setText( tpVO.getDescricao() );
            } catch (ParseException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    crDao.closeContasReceberDAO();
                } catch ( SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jcbTpPagtoActionPerformed

    private void jcbTpFormaCobrancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTpFormaCobrancaActionPerformed
        FormaCobrancaJurosVO fcjVO = new FormaCobrancaJurosVO();
        java.lang.String combo = String.valueOf(jcbTpFormaCobranca.getSelectedItem());
        fcjVO.setCodFormaCobrancaJuros(combo);
        if(fcjVO.getCodFormaCobrancaJuros()=="null"){
            lblFormaCobrancaJurosDescricao.setText("");
        }else{
            ContasReceberDAO crDao = null;
            try {
                crDao = new ContasReceberDAO();

                fcjVO = crDao.buscarFormaCobrancaJurosByCod(fcjVO);   
                lblFormaCobrancaJurosDescricao.setText( fcjVO.getDescricao() );

            } catch (ParseException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    crDao.closeContasReceberDAO();
                } catch ( SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jcbTpFormaCobrancaActionPerformed

    private void btoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSalvarActionPerformed
        ContasReceber1VO crVO; ContasReceberDAO crDao = null;
        try {
            crVO = new ContasReceber1VO();
            
//            crVO.getLblCodConta(lblCodConta.getText());
            crVO.setJcbEspDocumento(jcbEspDocumento.getSelectedItem().toString());
            crVO.setJcbFormaPagto(Integer.valueOf(jcbFormaPagto.getSelectedItem().toString()));
            crVO.setJcbSituacao(jcbSituacao.getSelectedItem().toString());
            crVO.setJcbTpFormaCobranca(jcbTpFormaCobranca.getSelectedItem().toString());
            crVO.setJcbTpPagto(jcbTpPagto.getSelectedItem().toString());
            crVO.setJftDtDocumento("  /  /    ".equals(jftDtDocumento.getText()) ? "null" : jftDtDocumento.getText());
            crVO.setJftDtQuitacao("  /  /    ".equals(jftDtQuitacao.getText()) ? "null" : jftDtQuitacao.getText());
            crVO.setJftDtVencimento("  /  /    ".equals(jftDtVencimento.getText()) ? "null" : jftDtVencimento.getText());
            crVO.setJrbTpTaxaJuros(jrbTpTaxaJuros.isSelected() ? "1" : "0");
            crVO.setJrbTpTaxaMulta(jrbTpTaxaMulta.isSelected() ? "1" : "0" );
            crVO.setJrbTpTitulo(jrbTpTitulo.isSelected() ? "1" : "0");
            crVO.setTxtCredor(jcbDevedor.getSelectedItem().toString().substring(0, jcbDevedor.getSelectedItem().toString().indexOf("-") ).trim());
            crVO.setTxtNumDocumento(txtNumDocumento.getText());
            crVO.setTxtTxJuros(jftTaxaJuros.getText()=="null" ? "0.00" : jftTaxaJuros.getText() );
            crVO.setTxtTxMulta(jftTxMulta.getText()=="null" ? "0.00" : jftTxMulta.getText() );
            crVO.setTxtVlDocumento(jftVlDocumento.getText()=="null" ? "0.00" : jftVlDocumento.getText());
            crVO.setTxtCodBarra(txtCodBarra.getText());
            crVO.setTxtVlReceber(txtVlPagar.getText()=="null" ? "0.00" : txtVlPagar.getText());
        
            crDao = new ContasReceberDAO();
            if(Integer.valueOf(crVO.getJcbFormaPagto().toString()) <= 1){
                crDao.salvarContasReceber(crVO);
            }else{
                crDao.salvarContasReceberParcelas(crVO);
            }
            
        } catch (ParseException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                crDao.closeContasReceberDAO();
                limpaCampos();
                
                btoIncluir.setEnabled(true); btoSalvar.setEnabled(false); btoAtualizar.setEnabled(false); btoExcluir.setEnabled(false);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btoSalvarActionPerformed

    private void btoLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoLocalizarActionPerformed
        ContasReceberDAO crDao=null; ContasReceber1VO crVO = null;
        List<ContasReceber1VO> dados = new ArrayList<ContasReceber1VO>();
        DefaultTableModel modelo;
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();  
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();  
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();  
  
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);  
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);  
        direita.setHorizontalAlignment(SwingConstants.RIGHT);  
  
        ConvertStringToDate conStringToData = null;
        FormataValor fv = null;
        java.util.Date data=null;
        //Busca registro conforme codogo da conta
        if(!"".equals(txtCodContaList.getText())){
            try {
                crDao = new ContasReceberDAO();
                conStringToData = new ConvertStringToDate(); fv = new FormataValor();
                dados = crDao.carregaJTableContasReceberByCodigo(Integer.valueOf(txtCodContaList.getText()));
                
                modelo = (DefaultTableModel) this.jTable1.getModel();
                modelo.setNumRows(0);
                for(ContasReceber1VO cr: dados){
                    try {
                        modelo.addRow(new String[]{String.valueOf(cr.getLblContasReceberPk()), (cr.getDevedorFk()+" - "+cr.getNomeDevedor()), conStringToData.convertStringToData(cr.getJftDtDocumento()) , cr.getTxtNumDocumento(), conStringToData.convertStringToData(cr.getJftDtVencimento()), fv.formatValor(cr.getTxtVlReceber()), cr.getJcbSituacao() } );
                    } catch (ParseException ex) {
                        Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                jTable1.getColumnModel().getColumn(0).setCellRenderer(direita);  
                jTable1.getColumnModel().getColumn(1).setCellRenderer(esquerda);  
                jTable1.getColumnModel().getColumn(2).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(3).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(4).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(5).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(6).setCellRenderer(esquerda);
                
                jTable1.setModel(modelo);
                //txtCodContaList.setText("");
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    crDao.closeContasReceberDAO();
                } catch ( SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        //Busca registro conforme periodo por data de vencimento
        if(!jftDtInicio.getText().equals("  /  /    ") && !jftDtFinal.getText().equals("  /  /    ")){
            try {
                crVO = new ContasReceber1VO();
                conStringToData = new ConvertStringToDate(); fv = new FormataValor();
                try {
                    crVO.setDataInicio(conStringToData.convertStringToDates(jftDtInicio.getText()));
                    crVO.setDataFim(conStringToData.convertStringToDates(jftDtFinal.getText()));
                } catch (ParseException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }                
                crDao = new ContasReceberDAO();
                dados = crDao.carregaJTableContasReceberByPeriodoVencimento(crVO);
                
                modelo = (DefaultTableModel) this.jTable1.getModel();
                modelo.setNumRows(0);
                for(ContasReceber1VO cr : dados){
                    try {
                        modelo.addRow(new String[]{String.valueOf(cr.getLblContasReceberPk()), (cr.getDevedorFk()+" - "+cr.getNomeDevedor()), conStringToData.convertStringToData(cr.getJftDtDocumento()) , cr.getTxtNumDocumento(), conStringToData.convertStringToData(cr.getJftDtVencimento()), fv.formatValor(cr.getTxtVlReceber()), cr.getJcbSituacao() } );
                    } catch (ParseException ex) {
                        Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                jTable1.getColumnModel().getColumn(0).setCellRenderer(direita);  
                jTable1.getColumnModel().getColumn(1).setCellRenderer(esquerda);  
                jTable1.getColumnModel().getColumn(2).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(3).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(4).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(5).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(6).setCellRenderer(esquerda);

                jTable1.setModel(modelo);//"  /  /    "
                //jftDtInicio.setText(null);jftDtFinal.setText(null);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    crDao.closeContasReceberDAO();
                } catch ( SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
        }
        //Busca registro conforme o nome do credor
        if(jcbDevedorList.getSelectedItem() != null){
            
        }
        //Busca registro conforme periodo e nome do credor
        if(!jftDtInicio.getText().equals("  /  /    ") && !jftDtFinal.getText().equals("  /  /    ") && jcbDevedorList.getSelectedItem() != null){
           try {
                crVO = new ContasReceber1VO();
                conStringToData = new ConvertStringToDate();
                try {
                    crVO.setDataInicio(conStringToData.convertStringToDates(jftDtInicio.getText()));
                    crVO.setDataFim(conStringToData.convertStringToDates(jftDtFinal.getText()));
                    //crVO.setNomeDevedor(jcbDevedorList.getSelectedItem().toString());
                    crVO.setDevedorFk( Integer.valueOf( jcbDevedorList.getSelectedItem().toString().substring(0, jcbDevedorList.getSelectedItem().toString().indexOf("-")).trim() ));
                } catch (ParseException ex) {
                    Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                }                
                crDao = new ContasReceberDAO();
                dados = crDao.carregaJTableContasReceberByVencimentoAndCredor(crVO);
                
                modelo = (DefaultTableModel) this.jTable1.getModel();
                modelo.setNumRows(0);
                for(ContasReceber1VO cr : dados){
                    try {
                        modelo.addRow(new String[]{String.valueOf(cr.getLblContasReceberPk()), (cr.getNomeDevedor()+" - "+cr.getDevedorFk()), conStringToData.convertStringToData(cr.getJftDtDocumento()) , cr.getTxtNumDocumento(), conStringToData.convertStringToData(cr.getJftDtVencimento()), fv.formatValor(cr.getTxtVlReceber()), cr.getJcbSituacao() } );
                    } catch (ParseException ex) {
                        Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                jTable1.getColumnModel().getColumn(0).setCellRenderer(direita);  
                jTable1.getColumnModel().getColumn(1).setCellRenderer(esquerda);  
                jTable1.getColumnModel().getColumn(2).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(3).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(4).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(5).setCellRenderer(direita);
                jTable1.getColumnModel().getColumn(6).setCellRenderer(esquerda);

                jTable1.setModel(modelo);
                //jftDtInicio.setText("  /  /    ");jftDtFinal.setText("  /  /    ");jcbDevedorList.setSelectedItem(null);
               } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
               } finally {
                    try {
                        crDao.closeContasReceberDAO();
                    } catch ( SQLException | ClassNotFoundException ex) {
                        Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
                    }
               }
        }
    }//GEN-LAST:event_btoLocalizarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linha = jTable1.getSelectedRow();
        ContasReceber1VO crVO = new ContasReceber1VO();
        crVO.setTxtCodContaList(String.valueOf( jTable1.getValueAt(linha, 0)));
        ConvertStringToDate convSTD = null; FormataValor fv = null;
        ContasReceberDAO crDao = null;
        try {
            crDao = new ContasReceberDAO();
            convSTD = new ConvertStringToDate();
            fv = new FormataValor();
            crVO = crDao.buscarContasReceberByPk(crVO);
            
            lblCodConta.setText(crVO.getLblCodConta());
            //jcbDevedorList.setSelectedItem(String.valueOf(crVO.getTxtCredor()));
            jcbEspDocumento.setSelectedItem(String.valueOf(crVO.getJcbEspDocumento()));
            jcbFormaPagto.setSelectedItem(crVO.getJcbFormaPagto());
            jcbSituacao.setSelectedItem(crVO.getJcbSituacao());
            jcbTpFormaCobranca.setSelectedItem(crVO.getJcbTpFormaCobranca());
            jcbTpPagto.setSelectedItem(crVO.getJcbTpPagto());
            jftDtDocumento.setText(convSTD.convertStringToData(crVO.getJftDtDocumento()));
            //jftDtFinal.setText(crVO.getJftDtFinal());
            //jftDtInicio.setText(crVO.getJftDtFinal());
            jftDtQuitacao.setText(convSTD.convertStringToData(crVO.getJftDtQuitacao()));
            jftDtVencimento.setText(convSTD.convertStringToData(crVO.getJftDtVencimento()));
            jrbTpTaxaJuros.setSelected("1".equals(crVO.getJrbTpTaxaMulta()) ? true : false);
            jrbTpTaxaMulta.setSelected("1".equals(crVO.getJrbTpTaxaMulta()) ? true : false);
            jrbTpTitulo.setSelected("1".equals(crVO.getJrbTpTitulo()) ? true : false);
            //jcbDevedor.addItem(crVO.getDevedorFk());
            jcbDevedor.setSelectedItem(crVO.getDevedorFk()+" - "+crVO.getNomeDevedor());
            lblDevedorNome.setText(crVO.getNomeDevedor());
            txtNumDocumento.setText(crVO.getTxtNumDocumento());
            jftTaxaJuros.setText(fv.formatValor(crVO.getTxtTxJuros()));
            jftTxMulta.setText(fv.formatValor(crVO.getTxtTxMulta()));
            jftVlDocumento.setText(fv.formatValor(crVO.getTxtVlDocumento()));
            txtVlPagar.setText(fv.formatValor(crVO.getTxtVlReceber()));
            
            btoIncluir.setEnabled(true);btoSalvar.setEnabled(false);
            btoAtualizar.setEnabled(true);btoExcluir.setEnabled(true);
            
        } catch (ParseException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                crDao.closeContasReceberDAO();
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jftDtDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftDtDocumentoFocusLost
//        if(!"".equals(jftDtDocumento.getText().replace("/","").trim())){
        if(!"  /  /    ".equals(jftDtDocumento.getText())){
            ValidaData vd = new ValidaData();
            boolean isData = vd.validarData(jftDtDocumento.getText());
            if(!isData){
                JOptionPane.showMessageDialog(this, "Data do documento nao é válida.");
                jftDtDocumento.setFocusable(true);
            }
        }
    }//GEN-LAST:event_jftDtDocumentoFocusLost

    private void jftDtVencimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftDtVencimentoFocusLost
//        if(!"".equals(jftDtVencimento.getText().replace("/","").trim())){
        if(!"  /  /    ".equals(jftDtVencimento.getText())){
            ValidaData vd = new ValidaData();
            boolean isData = vd.validarData(jftDtVencimento.getText());
            if(!isData){
                JOptionPane.showMessageDialog(this, "Data de vencimento nao é válida.");
                jftDtVencimento.setFocusable(true);
            }
        }
    }//GEN-LAST:event_jftDtVencimentoFocusLost

    private void jftDtQuitacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftDtQuitacaoFocusLost
        ValidaData vd = new ValidaData();
        if(!"  /  /    ".equals(jftDtQuitacao.getText())){
            boolean isData = vd.validarData(jftDtQuitacao.getText());
            if(!isData){
                JOptionPane.showMessageDialog(this, "Data de quitacao nao é válida.");
                jftDtQuitacao.setFocusable(true);
            }
        }
    }//GEN-LAST:event_jftDtQuitacaoFocusLost

    private void jftDtInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftDtInicioFocusLost
        ValidaData vd = new ValidaData();
        if(!"  /  /    ".equals(jftDtInicio.getText())){
            boolean isData = vd.validarData(jftDtInicio.getText());
            if(!isData){
                JOptionPane.showMessageDialog(this, "Data de início nao é válida.");
                jftDtInicio.setFocusable(true);
            }
        }
    }//GEN-LAST:event_jftDtInicioFocusLost

    private void jftDtFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftDtFinalFocusLost
        ValidaData vd = new ValidaData();
        if(!"  /  /    ".equals(jftDtFinal.getText())){
            boolean isData = vd.validarData(jftDtFinal.getText());
            if(!isData){
                JOptionPane.showMessageDialog(this, "Data final nao é válida.");
                jftDtFinal.setFocusable(true);
            }
        }
    }//GEN-LAST:event_jftDtFinalFocusLost

    private void txtVlPagarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlPagarFocusGained

        if(jcbFormaPagto.getSelectedItem() != null && !"".equals(jftVlDocumento.getText())){
            FormataValor fv = new FormataValor();
            java.lang.Double vlDocumento = Double.valueOf(jftVlDocumento.getText().replace(".","").replace(",","."));
            java.lang.Integer formaPagto = Integer.valueOf(jcbFormaPagto.getSelectedItem().toString());
            txtVlPagar.setText(fv.decimalFormat(String.valueOf(vlDocumento/formaPagto)));
        }
    }//GEN-LAST:event_txtVlPagarFocusGained

    private void jftVlDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftVlDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftVlDocumentoActionPerformed

    private void txtCodBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodBarraActionPerformed

    private void btoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoAtualizarActionPerformed
        ContasReceber1VO crVO; ContasReceberDAO crDao = null;
        try {
            crVO = new ContasReceber1VO();
            
            crVO.setLblCodConta(lblCodConta.getText());
            crVO.setJcbEspDocumento(jcbEspDocumento.getSelectedItem().toString());
            crVO.setJcbFormaPagto(Integer.valueOf(jcbFormaPagto.getSelectedItem().toString()));
            crVO.setJcbSituacao(jcbSituacao.getSelectedItem().toString());
            crVO.setJcbTpFormaCobranca(jcbTpFormaCobranca.getSelectedItem().toString());
            crVO.setJcbTpPagto(jcbTpPagto.getSelectedItem().toString());
            crVO.setJftDtDocumento(jftDtDocumento.getText());
            crVO.setJftDtQuitacao(jftDtQuitacao.getText());
            crVO.setJftDtVencimento(jftDtVencimento.getText());
            crVO.setJrbTpTaxaJuros(jrbTpTaxaJuros.isSelected() ? "1" : "0");
            crVO.setJrbTpTaxaMulta(jrbTpTaxaMulta.isSelected() ? "1" : "0" );
            crVO.setJrbTpTitulo(jrbTpTitulo.isSelected() ? "1" : "0");
            crVO.setTxtCredor(jcbDevedor.getSelectedItem().toString().substring(0, jcbDevedor.getSelectedItem().toString().indexOf("-")).trim());
            crVO.setTxtNumDocumento(txtNumDocumento.getText());
            crVO.setTxtTxJuros(jftTaxaJuros.getText()=="null" ? "0.00" : jftTaxaJuros.getText() );
            crVO.setTxtTxMulta(jftTxMulta.getText()=="null" ? "0.00" : jftTxMulta.getText() );
            crVO.setTxtVlDocumento(jftVlDocumento.getText()=="null" ? "0.00" : jftVlDocumento.getText());
            crVO.setTxtCodBarra("");
            crVO.setTxtVlReceber(txtVlPagar.getText()=="null" ? "0.00" : txtVlPagar.getText());
        
            crDao = new ContasReceberDAO();
            crDao.updateContasReceber(crVO);
            
        } catch (ParseException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                crDao.closeContasReceberDAO();
                limpaCampos();
                btoLocalizar.doClick();
                btoIncluir.setEnabled(true);btoAtualizar.setEnabled(false);btoExcluir.setEnabled(false);
                btoSalvar.setEnabled(false);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btoAtualizarActionPerformed

    private void jcbDevedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDevedorActionPerformed
    java.lang.String txt=null, nomeDevedor=null, codigoDevedor=null;
        if(jcbDevedor.getSelectedItem() != null && jcbDevedor.getSelectedItem().toString().length() > 4){
            txt = jcbDevedor.getSelectedItem().toString();
            codigoDevedor = txt.substring(0, txt.indexOf("-")).trim();
            nomeDevedor = txt.substring(txt.indexOf("-")).replace("-","").trim();
            //jcbDevedor.addItem(codigoDevedor);
            jcbDevedor.setSelectedItem(codigoDevedor+" - "+nomeDevedor);lblDevedorNome.setText(nomeDevedor);
        }
    }//GEN-LAST:event_jcbDevedorActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        btoSalvar.setEnabled(false);btoAtualizar.setEnabled(false);btoExcluir.setEnabled(false);
        ContasReceberDAO crDao=null; DevedorDAO dvDao=null; ConvertStringToDate cv; java.util.Date data;
        List<FormaPagtoVO> fpList; List<TipoPagtoVO> tpList; List<EspecieDocumentoVO> edList;
        List<SituacaoVO> stList;List<FormaCobrancaJurosVO> fcjList; List<DevedorVO> dvList;
        try {
            //Carrega combo Devedor
            dvDao = new DevedorDAO();
            dvList = dvDao.buscarAllDevedor();
            jcbDevedor.addItem(null);jcbDevedorList.addItem(null);
            if(!dvList.equals(null))
	            for(DevedorVO devedor : dvList){
	                jcbDevedor.addItem(devedor.getDevedorPk()+" - "+devedor.getNomeDevedor());
	                jcbDevedorList.addItem(devedor.getDevedorPk()+" - "+devedor.getNomeDevedor());
	            }
            //Codigo que carrega o campo data documento com a data atual do SO.
            data = new Date();
            cv = new ConvertStringToDate();
            jftDtDocumento.setText(cv.convertStringToData((data.getYear()+1900)+"-"+((data.getMonth()+1)<10 ? "0"+String.valueOf(data.getMonth()+1) : data.getMonth()+1 )+"-"+(data.getDate()<10 ? "0"+String.valueOf(data.getDate()) : data.getDate()) ));
            //Codigo para cerregar as combos da tela
            crDao = new ContasReceberDAO();
            fpList = new ArrayList(); tpList = new ArrayList(); edList = new ArrayList();
            //Carrega combo Forma de Pagto
            fpList = crDao.buscarFormaPagto();
            jcbFormaPagto.addItem(null);
            for(FormaPagtoVO formas : fpList){
                jcbFormaPagto.addItem(formas.getCodForma());
            }
            //Carrega combo Tipo de Pagto
            tpList = crDao.buscarTipoPagto();
            jcbTpPagto.addItem(null);
            for(TipoPagtoVO tiposPg : tpList){
                jcbTpPagto.addItem(tiposPg.getCodTpPagto());
            }
            //Carrega combo Especie
            edList = crDao.buscarEspecieDocumento();
            jcbEspDocumento.addItem(null);
            for(EspecieDocumentoVO especies : edList){
                jcbEspDocumento.addItem(especies.getCodEspDocumento());
            }
            //Carrega combo Situacao
            stList = crDao.buscarSituacaoContasReceber();
            jcbSituacao.addItem(null);
            for(SituacaoVO situacoes : stList){
                jcbSituacao.addItem(situacoes.getDescricao());
            }
            //Carrega combo forma de cobranca
            fcjList = crDao.buscarFormaCobrancaJuros();
            jcbTpFormaCobranca.addItem(null);
            for(FormaCobrancaJurosVO fCobranca : fcjList){
                jcbTpFormaCobranca.addItem(fCobranca.getCodFormaCobrancaJuros());
            }
        
        } catch (ParseException | SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                crDao.closeContasReceberDAO();
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        jcbDevedor.removeAllItems(); jcbDevedorList.removeAllItems();
        jftDtDocumento.setText(""); jcbFormaPagto.removeAllItems();
        jcbTpPagto.removeAllItems(); jcbEspDocumento.removeAllItems();
        jcbSituacao.removeAllItems(); jcbTpFormaCobranca.removeAllItems();
    }//GEN-LAST:event_formInternalFrameClosing

    private void btoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoExcluirActionPerformed
        ContasReceber1VO crVO = null; ContasReceberDAO crDao = null;
        try {
            crVO = new ContasReceber1VO();
            crVO.setLblContasReceberPk(Integer.valueOf(lblCodConta.getText()));

            crDao = new ContasReceberDAO();
            crDao.deleteContasReceber(crVO);
            //Chama método recursivammente para carregar o grid com a exclusao
            btoLocalizar.doClick();
        } catch (SQLException | ClassNotFoundException | ParseException ex) {
            Logger.getLogger(ContasPagar.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                crDao.closeContasReceberDAO();
                limpaCampos();
                
                btoIncluir.setEnabled(true);btoAtualizar.setEnabled(false);btoExcluir.setEnabled(false);
                btoSalvar.setEnabled(false);
            } catch ( SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContasPagar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btoExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoAtualizar, btoExcluir, btoIncluir, btoLocalizar, btoSalvar;

    private javax.swing.JScrollPane jScrollPane1;
    
    private javax.swing.JTable jTable1;
    
    private javax.swing.JComboBox jcbDevedor , jcbDevedorList, jcbEspDocumento, jcbFormaPagto, jcbSituacao, jcbTpFormaCobranca, jcbTpPagto;
    
    private javax.swing.JFormattedTextField jftDtDocumento, jftDtFinal, jftDtInicio, jftDtQuitacao, jftDtVencimento, jftTaxaJuros,
    jftTxMulta, jftVlDocumento;
    
    private javax.swing.JPanel jpBotao, jpCampos, jpLista; 
    
    private javax.swing.JRadioButton jrbTpTaxaJuros, jrbTpTaxaMulta, jrbTpTitulo;
    
    private javax.swing.JLabel lblCod, lblCodBarras, lblCodConta, lblCodContaList, lblCredor, lblCredorList, lblDevedorNome, lblDtDocumento,
    lblDtFinal, lblDtQuitacao, lblEspDocumento, lblEspDocumentoDescicao, lblFormaCobrancaJurosDescricao, lblFormaPagto, lblFormaPagtoDescricao,
    lblNumDocumento, lblSituacao, lblTpFormaPagto, lblTpPagto, lblTpPagtoDescricao, lblTxJuros, lblTxMulta, lblVlDocumento, lblVlPagar,
    lvlDtVencimento, jLabel17;
    
    private javax.swing.JTextField txtCodBarra, txtCodContaList, txtNumDocumento, txtVlPagar;
    
    private ControlMoto telaControlMoto;
    
    static int openFrameCount = 10;
    static final int xOffset = 4, yOffset = 4;
    
    // End of variables declaration//GEN-END:variables

    private void limpaCampos(){
        jcbEspDocumento.setSelectedItem(null);
        jcbFormaPagto.setSelectedItem(null);
        jcbSituacao.setSelectedItem("A vencer");
        jcbTpFormaCobranca.setSelectedItem(null);
        jcbTpPagto.setSelectedItem(null);
        jftDtDocumento.setText("");
        jftDtQuitacao.setText("");
        jftDtVencimento.setText("");
        jftTaxaJuros.setText("");
        jftTxMulta.setText("");
        jftVlDocumento.setText("");
        lblCodConta.setText("");
        txtCodBarra.setText("");
        lblDevedorNome.setText("");
        jcbDevedor.setSelectedItem(null);
        txtNumDocumento.setText("");
        txtVlPagar.setText("");
    }
}
