/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cs.controlmoto.controller;

import java.awt.Dialog;
import java.io.File;
import java.text.ParseException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import br.com.cs.controlmoto.domain.ConnectionFactory;
import br.com.cs.controlmoto.utils.ConvertStringToDate;
import br.com.cs.controlmoto.utils.LerArquivo;
import br.com.cs.controlmoto.vo.LerArquivoVO;

/**
 * Company Fictec Consul. Inf.
 * @author Clovis
 * @version 1.0.1
 * @since 17092012
 */
public class RelatFinaceiro extends javax.swing.JInternalFrame {

    /**
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Relatorio
     */
    public RelatFinaceiro(String titulo, ControlMoto controlMoto) {
        initComponents(titulo, controlMoto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String titulo, ControlMoto controlMoto) {

        btgOpcoes = new javax.swing.ButtonGroup();
        jpOpcao = new javax.swing.JPanel();
        jrbFluxoCaixa = new javax.swing.JRadioButton();
        jrbGastos = new javax.swing.JRadioButton();
        jrbProventos = new javax.swing.JRadioButton();
        jrbInvestimentos = new javax.swing.JRadioButton();
        jrbFaturaCC = new javax.swing.JRadioButton();
        jpDados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jftDataInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jftDataTermino = new javax.swing.JFormattedTextField();
        btoAbrir = new javax.swing.JButton();
        
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
        this.telaControlMoto = telaControlMoto;
    	controlMoto.jDesktopPane.add(this);

        setClosable(true);
        setIconifiable(true);
        setTitle("Relatórios do Financeiro");
        setToolTipText("Relatório do Financeiro");

        jpOpcao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opção de Relatório", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        btgOpcoes.add(jrbFluxoCaixa);
        jrbFluxoCaixa.setText("Fluxo de Caixa");

        btgOpcoes.add(jrbGastos);
        jrbGastos.setText("Gastos");

        btgOpcoes.add(jrbProventos);
        jrbProventos.setText("Proventos");

        btgOpcoes.add(jrbInvestimentos);
        jrbInvestimentos.setText("Investimentos");

        btgOpcoes.add(jrbFaturaCC);
        jrbFaturaCC.setText("Fatura CC");

        javax.swing.GroupLayout jpOpcaoLayout = new javax.swing.GroupLayout(jpOpcao);
        jpOpcao.setLayout(jpOpcaoLayout);
        jpOpcaoLayout.setHorizontalGroup(
            jpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOpcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbInvestimentos)
                    .addGroup(jpOpcaoLayout.createSequentialGroup()
                        .addComponent(jrbFluxoCaixa)
                        .addGap(18, 18, 18)
                        .addComponent(jrbFaturaCC))
                    .addComponent(jrbGastos)
                    .addComponent(jrbProventos))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jpOpcaoLayout.setVerticalGroup(
            jpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOpcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFluxoCaixa)
                    .addComponent(jrbFaturaCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbProventos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbInvestimentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Período do Relatório", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 204)));

        jLabel1.setText("Data Início");

        try {
            jftDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("Data Término");

        try {
            jftDataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataTermino.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftDataTermino.setToolTipText("Data final para gerar o relatório.");

        btoAbrir.setText("Abrir");
        btoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDataTermino, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btoAbrir)))
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jftDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btoAbrir)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpOpcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoAbrirActionPerformed
        java.sql.Connection minhaConexao=null; ConvertStringToDate cv = null;
        java.util.Date dataInicio = null, dataTermino = null;
        /* Abre relatorio de fluxo de caixa   */
        if(jrbFluxoCaixa.isSelected() && !"null".equals(jftDataInicio.getText()) && !"null".equals(jftDataTermino.getText())){
            try {
                cv = new ConvertStringToDate();
                dataInicio = cv.convertStringToDates( jftDataInicio.getText() );
                dataTermino = cv.convertStringToDates( jftDataTermino.getText() );
                //Pega caminho da aplicação
                caminho = new File("").getAbsolutePath();
                //Pega o caracter de separação de pastas do sistema
                separadorPath = System.getProperty("file.separator");
                //Le o arquivo txt para pegar o camonho dos relatórios 
                //this.caminhoReport();

                JasperPrint relat=null;           
                //Conexao ao banco de dados
                minhaConexao = ConnectionFactory.getConnection();
                HashMap map = new HashMap();
                map.put("dataInicio",dataInicio);
                map.put("dataFinal",dataTermino);
                //Caminho para o arquivo de relatorio
//                String report = "../ControlMoto/reports/";
                //Nome do arquivo de relatorio
                String arquivoJasper = "rpt_fluxocaixa.jasper";
    			if(!caminho.contains("workspace")){
    				//CAMINHO DE PRODUCAO
    				relat = JasperFillManager.fillReport(caminho+separadorPath+"reports"+separadorPath+arquivoJasper, map, minhaConexao);
    			}else{
    				//CAMINHO DE ECLIPSE
    				relat = JasperFillManager.fillReport(caminho+separadorPath+"reports"+separadorPath+arquivoJasper, map, minhaConexao);
    			}
                //relat = JasperFillManager.fillReport(report+arquivoJasper, map, minhaConexao);
                JasperViewer jasperViewer = new JasperViewer(relat, false);
                jasperViewer.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
                jasperViewer.setTitle("ControlMoto - Fluxo de Caixa");
                jasperViewer.setZoomRatio(0.75f);
                jasperViewer.setBounds(100,110,750,600);
                //caminho para producao
                //ImageIcon icone = new ImageIcon(caminho+separadorPath+logo_tipo+"logo_cs_b.gif");
                //caminho para eclipse
                //ImageIcon icone = new ImageIcon(logo_tipo+"logo_cs_b.gif");
                //ImageIcon icone = new ImageIcon(caminho+separadorPath+lerArquivoVO.getLogoTipo()+separadorPath+"logo_cs_b.gif");
                //jasperViewer.setIconImage(icone.getImage());
                jasperViewer.setAlwaysOnTop(true);
                jasperViewer.setVisible(true);
            } catch( ParseException | JRException ex){
                Logger.getLogger(ControlMoto.class.getName()).log(Level.SEVERE, null, ex);
            } catch( Exception ex ){
                Logger.getLogger(ControlMoto.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }
        /* Abre relatorio de fatura de cartao de credito  */
        if(jrbFaturaCC.isSelected() && !"null".equals(jftDataInicio.getText()) && !"null".equals(jftDataTermino.getText())){
            try {
                cv = new ConvertStringToDate();
                dataInicio = cv.convertStringToDates( jftDataInicio.getText() );
                dataTermino = cv.convertStringToDates( jftDataTermino.getText() );

                JasperPrint relat=null;           
                //Conexao ao banco de dados
                minhaConexao = ConnectionFactory.getConnection();
                HashMap map = new HashMap();
                map.put("dataInicio",dataInicio);
                map.put("dataFinal",dataTermino);
                //Caminho para o arquivo de relatorio
                String report = "../ControlMoto/reports/";
                //Nome do arquivo de relatorio
                String arquivoJasper = "rpt_fatura_cc.jasper";
                relat = JasperFillManager.fillReport(report+arquivoJasper, map, minhaConexao);
                JasperViewer jasperViewer = new JasperViewer(relat, false);
                jasperViewer.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
                jasperViewer.setTitle("ControlMoto - Fatura Cartão de Crédito ");
                jasperViewer.setZoomRatio(0.75f);
                jasperViewer.setBounds(100,110,750,600);
                //caminho para producao
                //ImageIcon icone = new ImageIcon(caminho+separadorPath+logo_tipo+"logo_cs_b.gif");
                //caminho para eclipse
                //ImageIcon icone = new ImageIcon(logo_tipo+"logo_cs_b.gif");
                //ImageIcon icone = new ImageIcon(caminho+separadorPath+lerArquivoVO.getLogoTipo()+separadorPath+"logo_cs_b.gif");
                //jasperViewer.setIconImage(icone.getImage());
                jasperViewer.setAlwaysOnTop(true);
                jasperViewer.setVisible(true);
            } catch( ParseException | JRException ex){
                Logger.getLogger(ControlMoto.class.getName()).log(Level.SEVERE, null, ex);
            } catch( Exception ex ){
                Logger.getLogger(ControlMoto.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }
        /* Abre relatorio de gastos  */
        if(jrbGastos.isSelected() && !"null".equals(jftDataInicio.getText()) && !"null".equals(jftDataTermino.getText())){
            try {
                cv = new ConvertStringToDate();
                dataInicio = cv.convertStringToDates( jftDataInicio.getText() );
                dataTermino = cv.convertStringToDates( jftDataTermino.getText() );

                JasperPrint relat=null;           
                //Conexao ao banco de dados
                minhaConexao = ConnectionFactory.getConnection();
                HashMap map = new HashMap();
                map.put("dataInicio",dataInicio);
                map.put("dataFinal",dataTermino);
                //Caminho para o arquivo de relatorio
                String report = "../ControlMoto/reports/";
                //Nome do arquivo de relatorio
                String arquivoJasper = "rpt_gastospordespesa.jasper";
                relat = JasperFillManager.fillReport(report+arquivoJasper, map, minhaConexao);
                JasperViewer jasperViewer = new JasperViewer(relat, false);
                jasperViewer.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
                jasperViewer.setTitle("ControlMoto - Gastos Mensais");
                jasperViewer.setZoomRatio(0.75f);
                jasperViewer.setBounds(100,110,750,600);
                //caminho para producao
                //ImageIcon icone = new ImageIcon(caminho+separadorPath+logo_tipo+"logo_cs_b.gif");
                //caminho para eclipse
                //ImageIcon icone = new ImageIcon(logo_tipo+"logo_cs_b.gif");
                //ImageIcon icone = new ImageIcon(caminho+separadorPath+lerArquivoVO.getLogoTipo()+separadorPath+"logo_cs_b.gif");
                //jasperViewer.setIconImage(icone.getImage());
                jasperViewer.setAlwaysOnTop(true);
                jasperViewer.setVisible(true);
            } catch( ParseException | JRException ex){
                Logger.getLogger(ControlMoto.class.getName()).log(Level.SEVERE, null, ex);
            } catch( Exception ex ){
                Logger.getLogger(ControlMoto.class.getName()).log(Level.SEVERE, null, ex);
            }        
        }        
    }//GEN-LAST:event_btoAbrirActionPerformed

    private ControlMoto telaControlMoto;
    
    static int openFrameCount = 19;
    static final int xOffset = 16, yOffset = 10;
    
    static java.lang.String caminho, separadorPath, report;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgOpcoes;
    private javax.swing.JButton btoAbrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField jftDataInicio;
    private javax.swing.JFormattedTextField jftDataTermino;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpOpcao;
    private javax.swing.JRadioButton jrbFaturaCC;
    private javax.swing.JRadioButton jrbFluxoCaixa;
    private javax.swing.JRadioButton jrbGastos;
    private javax.swing.JRadioButton jrbInvestimentos;
    private javax.swing.JRadioButton jrbProventos;
    // End of variables declaration//GEN-END:variables
    
	public String caminhoReport(){
		LerArquivoVO lerArquivoVO = new LerArquivoVO();
		LerArquivo lerArquivo = new LerArquivo();
		lerArquivoVO = lerArquivo.getInformacao(lerArquivoVO);
		return report = String.valueOf(lerArquivoVO.getReports());
	}
}
