/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cs.controlmoto.controller;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import br.com.cs.controlmoto.domain.AgendamentoDAO;
import br.com.cs.controlmoto.domain.CadClienteDAO;
import br.com.cs.controlmoto.domain.CadMotoristaDAO;
import br.com.cs.controlmoto.domain.TarefaDAO;
import br.com.cs.controlmoto.utils.ConvertStringToDate;
import br.com.cs.controlmoto.vo.AgendamentoVO;
import br.com.cs.controlmoto.vo.CadClienteVO;
import br.com.cs.controlmoto.vo.CadMotoristaVO;
import br.com.cs.controlmoto.vo.TarefaVO;

/**
 *
 * @author Fictec
 */
public class TabAgenda extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/**
     * Creates new form TabAgenda
     */
    public TabAgenda(String titulo, ControlMoto controlMoto) {
        initComponents(titulo, controlMoto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String titulo, ControlMoto controlMoto) {
    	
    	caminho = new File("").getAbsolutePath();
    	separadorPath = System.getProperty("file.separator");

        bgOpcao = new javax.swing.ButtonGroup();
        jtbBarraFerramenta = new javax.swing.JToolBar();
        jtbBarraFerramenta.setPreferredSize(new Dimension(660,50));
        btoNovo = new javax.swing.JButton(); btoNovo.setToolTipText("Novo");
        btoNovo.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"hd_folha_novo_16x16.png"));
        btoSalvar = new javax.swing.JButton(); btoSalvar.setToolTipText("Gravar");
        btoSalvar.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"hd_flopy_16x16.png")); 
        btoAlterar = new javax.swing.JButton(); btoAlterar.setToolTipText("Atualizar"); 
        btoAlterar.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"hd_atualiza_16x16.png"));
        btoCancelar = new javax.swing.JButton(); btoCancelar.setToolTipText("Cancelar"); 
        btoCancelar.setIcon(new ImageIcon(caminho + separadorPath + "imagens" + separadorPath + "icone" + separadorPath + "hd_cancela_16x16.png"));
        btoImprimir = new javax.swing.JButton(); btoImprimir.setToolTipText("Imprimir"); 
        btoImprimir.setIcon(new ImageIcon(caminho+separadorPath+"imagens"+separadorPath+"icone"+separadorPath+"impressora_empresa_16x16.png"));
        btoLocalizar = new javax.swing.JButton(); btoLocalizar.setToolTipText("Localizar"); 
        btoLocalizar.setIcon(new ImageIcon(caminho + separadorPath + "imagens" + separadorPath + "icone" + separadorPath + "hd_lupa_16x16.png"));
        
        jSeparator1 = new javax.swing.JToolBar.Separator();
        
        jrbPrevisto = new javax.swing.JRadioButton(); jrbAtrasado = new javax.swing.JRadioButton(); jrbEnviado = new javax.swing.JRadioButton();
        jrbCancelado = new javax.swing.JRadioButton(); jrbTodos = new javax.swing.JRadioButton();
        
        jpSupAgenda = new javax.swing.JPanel(); jpSuperior = new javax.swing.JPanel(); jpRodape = new javax.swing.JPanel();
        jpEsquerdo = new javax.swing.JPanel(); jpDireito = new javax.swing.JPanel();
        
        lblCodigo = new javax.swing.JLabel(); lblValorCodigo = new javax.swing.JLabel(); lblStatus = new javax.swing.JLabel();
        lblValorStatus = new javax.swing.JLabel(); lblData = new javax.swing.JLabel(); lblTarefa = new javax.swing.JLabel("Tarefa");
        lblHora = new javax.swing.JLabel(); lblCliente = new javax.swing.JLabel(); lblMotorista = new javax.swing.JLabel();
        lblNumeroOS = new javax.swing.JLabel(); lblValorNumeroOS = new javax.swing.JLabel(); lblAtrasado = new javax.swing.JLabel("#");
        lblAtrasado.setForeground(Color.RED);
        
        jftDataAgendamento = new javax.swing.JFormattedTextField();
        
        jftHoraAgendamento = new javax.swing.JFormattedTextField();
        
        jcbCliente = new javax.swing.JComboBox(); jcbTarefa = new javax.swing.JComboBox(); jcbMotorista = new javax.swing.JComboBox();
        
        jScrollPane1 = new javax.swing.JScrollPane(); jScrollPane2 = new javax.swing.JScrollPane();
        
        jtAgenda = new javax.swing.JTable(); jtTarefa = new javax.swing.JTable();
        
        jmcMes = new com.toedter.calendar.JMonthChooser(); jycAno = new com.toedter.calendar.JYearChooser();
        jdcDia = new com.toedter.calendar.JDayChooser();
        
        modTarefa = true; modAgenda = true;

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setClosable(true);
        setIconifiable(true);
        setTitle("Agenda");
        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(660, 620));
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            public void windowActivated(java.awt.event.WindowEvent evt) {
//                formWindowActivated(evt);
//            }
//        });
        
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
//                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
        this.telaControlMoto = telaControlMoto;
    	controlMoto.jDesktopPane.add(this);

        jtbBarraFerramenta.setFloatable(false);
        jtbBarraFerramenta.setRollover(true);
        jtbBarraFerramenta.setToolTipText("Barra de Ferramenta Agenda");

        btoNovo.setText("");
        btoNovo.setFocusable(false);
        btoNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoNovoActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btoNovo);

        btoSalvar.setText("");
        btoSalvar.setFocusable(false);
        btoSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSalvarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btoSalvar);

        btoLocalizar.setText("");
        btoLocalizar.setFocusable(false);
        btoLocalizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoLocalizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btoLocalizarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btoLocalizar);
        
        btoAlterar.setText("");
        btoAlterar.setFocusable(false);
        btoAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoAlterarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btoAlterar);

        btoCancelar.setText("");
        btoCancelar.setFocusable(false);
        btoCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoCancelarActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btoCancelar);

        btoImprimir.setText("");
        btoImprimir.setFocusable(false);
        btoImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btoImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoImprimirActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(btoImprimir);
        jtbBarraFerramenta.add(jSeparator1);
        
        bgOpcao.add(jrbTodos);
        jrbTodos.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jrbTodos.setSelected(true);
        jrbTodos.setText("Todos");
        jrbTodos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrbTodos.setFocusable(false);
        jrbTodos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jrbTodos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jrbTodos.setMargin(new java.awt.Insets(4, 2, 2, 2));
        jrbTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jrbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jrbTodosActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(jrbTodos);

        bgOpcao.add(jrbPrevisto);
        jrbPrevisto.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jrbPrevisto.setText("Previsto");
        jrbPrevisto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrbPrevisto.setFocusable(false);
        jrbPrevisto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jrbPrevisto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jrbPrevisto.setMargin(new java.awt.Insets(4, 2, 2, 2));
        jrbPrevisto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jrbPrevisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPrevistoActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(jrbPrevisto);

        bgOpcao.add(jrbAtrasado);
        jrbAtrasado.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jrbAtrasado.setText("Atrasado");
        jrbAtrasado.setFocusable(false);
        jrbAtrasado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jrbAtrasado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jrbAtrasado.setMargin(new java.awt.Insets(5, 2, 5, 2));
        jrbAtrasado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jrbAtrasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAtrasadoActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(jrbAtrasado);

        bgOpcao.add(jrbEnviado);
        jrbEnviado.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jrbEnviado.setText("Enviado");
        jrbEnviado.setFocusable(false);
        jrbEnviado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jrbEnviado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jrbEnviado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jrbEnviado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEnviadoActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(jrbEnviado);

        bgOpcao.add(jrbCancelado);
        jrbCancelado.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jrbCancelado.setText("Cancelado");
        jrbCancelado.setFocusable(false);
        jrbCancelado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jrbCancelado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jrbCancelado.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jrbCancelado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jrbCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCanceladoActionPerformed(evt);
            }
        });
        jtbBarraFerramenta.add(jrbCancelado);

        jpSupAgenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agendamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        jpSupAgenda.setMaximumSize(new java.awt.Dimension(640, 144));
        jpSupAgenda.setMinimumSize(new java.awt.Dimension(640, 10));
        jpSupAgenda.setPreferredSize(new java.awt.Dimension(640, 144));

        lblCodigo.setText("Código");

        lblValorCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        lblValorCodigo.setMaximumSize(new java.awt.Dimension(38, 19));
        lblValorCodigo.setMinimumSize(new java.awt.Dimension(38, 19));
        lblValorCodigo.setPreferredSize(new java.awt.Dimension(38, 19));

        lblStatus.setText("Situação");

        lblValorStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        lblValorStatus.setMaximumSize(new java.awt.Dimension(38, 19));
        lblValorStatus.setMinimumSize(new java.awt.Dimension(38, 19));
        lblValorStatus.setPreferredSize(new java.awt.Dimension(38, 19));

        lblData.setText("Data");

        try {
            jftDataAgendamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataAgendamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftDataAgendamento.setToolTipText("Data Agendamento");

        lblHora.setText("Hora");

        try {
            jftHoraAgendamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftHoraAgendamento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftHoraAgendamento.setToolTipText("Hora agendamento");

        lblCliente.setText("Cliente");

        lblMotorista.setText("Motorista");

        lblNumeroOS.setText("Número O.S.");

        lblValorNumeroOS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorNumeroOS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        lblValorNumeroOS.setMaximumSize(new java.awt.Dimension(38, 19));
        lblValorNumeroOS.setMinimumSize(new java.awt.Dimension(38, 19));
        lblValorNumeroOS.setPreferredSize(new java.awt.Dimension(38, 19));
        
        colModelTarefa = jtTarefa.getColumnModel(); colModelAgenda = jtAgenda.getColumnModel();
        tcrEsqueda = new DefaultTableCellRenderer();tcrEsqueda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    	tcrDireta = new DefaultTableCellRenderer();tcrDireta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    	tcrCentro = new DefaultTableCellRenderer();tcrCentro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpSupAgendaLayout = new javax.swing.GroupLayout(jpSupAgenda);
        jpSupAgenda.setLayout(jpSupAgendaLayout);
        jpSupAgendaLayout.setHorizontalGroup(
                jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSupAgendaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpSupAgendaLayout.createSequentialGroup()
                            .addComponent(lblMotorista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbMotorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpSupAgendaLayout.createSequentialGroup()
                            .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodigo)
                                .addComponent(lblData))
                            .addGap(18, 18, 18)
                            .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jftDataAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(lblValorCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpSupAgendaLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                    .addComponent(lblHora)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jftHoraAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65))
                                .addGroup(jpSupAgendaLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTarefa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNumeroOS)
                                .addComponent(lblStatus))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblValorStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(lblValorNumeroOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jpSupAgendaLayout.createSequentialGroup()
                            .addComponent(lblCliente)
                            .addGap(18, 18, 18)
                            .addComponent(jcbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jpSupAgendaLayout.setVerticalGroup(
                jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSupAgendaLayout.createSequentialGroup()
                    .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(lblValorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStatus)
                        .addComponent(lblValorStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTarefa)
                        .addComponent(jcbTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblData)
                        .addComponent(jftDataAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHora)
                        .addComponent(jftHoraAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumeroOS)
                        .addComponent(lblValorNumeroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCliente)
                        .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jpSupAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMotorista)
                        .addComponent(jcbMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 15, Short.MAX_VALUE))
            );

        javax.swing.GroupLayout jpSuperiorLayout = new javax.swing.GroupLayout(jpSuperior);
        jpSuperior.setLayout(jpSuperiorLayout);
        jpSuperiorLayout.setHorizontalGroup(
            jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbBarraFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpSuperiorLayout.createSequentialGroup()
                .addComponent(jpSupAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jpSuperiorLayout.setVerticalGroup(
            jpSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSuperiorLayout.createSequentialGroup()
                .addComponent(jtbBarraFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSupAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jpSuperior, java.awt.BorderLayout.PAGE_START);

        jpRodape.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        jpRodape.setToolTipText("Agenda");

        jtAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Hora", "Cliente", "Tarefa", "Status", "Motorista", "Núm. OS."
            }
        ));
        jtAgenda.addMouseListener(new java.awt.event.MouseAdapter(){
        	public void mouseClicked(java.awt.event.MouseEvent evt){
        		jtAgendaMouseClicked(evt);
        	}
        });
        
		jtAgenda.getColumnModel().getColumn(0).setPreferredWidth(40);colModelAgenda.getColumn(0).setCellRenderer(tcrDireta);
		jtAgenda.getColumnModel().getColumn(1).setPreferredWidth(60);colModelAgenda.getColumn(1).setCellRenderer(tcrDireta);
		jtAgenda.getColumnModel().getColumn(2).setPreferredWidth(30);colModelAgenda.getColumn(2).setCellRenderer(tcrDireta);
		jtAgenda.getColumnModel().getColumn(3).setPreferredWidth(100);
		jtAgenda.getColumnModel().getColumn(4).setPreferredWidth(50);
		jtAgenda.getColumnModel().getColumn(5).setPreferredWidth(50);
		jtAgenda.getColumnModel().getColumn(6).setPreferredWidth(100);colModelAgenda.getColumn(6).setCellRenderer(tcrEsqueda);
		jtAgenda.getColumnModel().getColumn(7).setPreferredWidth(50);colModelAgenda.getColumn(7).setCellRenderer(tcrDireta);
		
        jScrollPane1.setViewportView(jtAgenda);

        javax.swing.GroupLayout jpRodapeLayout = new javax.swing.GroupLayout(jpRodape);
        jpRodape.setLayout(jpRodapeLayout);
        jpRodapeLayout.setHorizontalGroup(
            jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpRodapeLayout.setVerticalGroup(
            jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRodapeLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpRodape, java.awt.BorderLayout.PAGE_END);

        jpEsquerdo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calendário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153))));
        jpEsquerdo.setToolTipText("Calendário");
        jpEsquerdo.setMaximumSize(new java.awt.Dimension(340, 210));
        jpEsquerdo.setPreferredSize(new java.awt.Dimension(320, 190));

        jmcMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmcMesMouseClicked(evt);
            }
        });
        jmcMes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jmcMesPropertyChange(evt);
            }
        });

        jycAno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jycAnoPropertyChange(evt);
            }
        });

        jdcDia.setMaximumSize(new java.awt.Dimension(340, 200));
        jdcDia.setMonth(jmcMes.getMonth());
        jdcDia.setYear(jycAno.getYear());
        jdcDia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcDiaPropertyChange(evt);
            }
        });
        
        javax.swing.GroupLayout jpEsquerdoLayout = new javax.swing.GroupLayout(jpEsquerdo);
        jpEsquerdo.setLayout(jpEsquerdoLayout);
        jpEsquerdoLayout.setHorizontalGroup(
            jpEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEsquerdoLayout.createSequentialGroup()
                .addGroup(jpEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpEsquerdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jdcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEsquerdoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jmcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jycAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jpEsquerdoLayout.setVerticalGroup(
            jpEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEsquerdoLayout.createSequentialGroup()
                .addGroup(jpEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmcMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jycAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        getContentPane().add(jpEsquerdo, java.awt.BorderLayout.CENTER);

        jpDireito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tarefa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));
        jpDireito.setToolTipText("Tarefa");
        jpDireito.setMaximumSize(new java.awt.Dimension(300, 190));
        jpDireito.setPreferredSize(new java.awt.Dimension(300, 190));

        jtTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tarefas"
            }
        ));
        
        jtTarefa.getColumnModel().getColumn(0).setPreferredWidth(10);colModelTarefa.getColumn(0).setCellRenderer(tcrDireta);
        jtTarefa.getColumnModel().getColumn(1).setPreferredWidth(70);

        jtTarefa.setMaximumSize(new java.awt.Dimension(290, 220));
        jtTarefa.setMinimumSize(new java.awt.Dimension(200, 150));
        jtTarefa.setPreferredSize(new java.awt.Dimension(270, 200));
        jScrollPane2.setViewportView(jtTarefa);

        javax.swing.GroupLayout jpDireitoLayout = new javax.swing.GroupLayout(jpDireito);
        jpDireito.setLayout(jpDireitoLayout);
        jpDireitoLayout.setHorizontalGroup(
            jpDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDireitoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpDireitoLayout.setVerticalGroup(
            jpDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDireitoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        btoNovo.setEnabled(true); btoSalvar.setEnabled(false); btoLocalizar.setEnabled(true); btoAlterar.setEnabled(false);
        btoCancelar.setEnabled(true); btoImprimir.setEnabled(false);

        getContentPane().add(jpDireito, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>                        
//    private void addWindowListener(WindowAdapter windowAdapter) {
//        jpSupAgenda.setEnabled(false); jpSupAgenda.setVisible(false);
//        jpSupAgenda.setPreferredSize(new java.awt.Dimension(0, 0));
//        
//       AgendamentoVO agendamentoBean = new AgendamentoVO();
//        try {
//            //CARREGA O GRID DE TAREFAS
//            List<TarefaVO> tarefaBeans = new ArrayList<>();
//                tarefaBeans = new TarefaDAO().getAllTarefa();
//
//            modeloTarefa = (DefaultTableModel) jtTarefa.getModel();
//            for(TarefaVO trBean : tarefaBeans)
//                modeloTarefa.addRow(new String[]{String.valueOf(trBean.getTarefaPk()), trBean.getDescricaoTarefa()});
//            //CARREGA O GRID DA AGENDA
//            agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
//            List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
//            agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAno(agendamentoBean);
//            
//            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
//            for(AgendamentoVO agBean : agendamentoBeans)
//                modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), agBean.getHrAgendada(), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });
//                        
//        } catch (ClassNotFoundException | SQLException | IllegalAccessException | InstantiationException ex) {
//            Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
//        }finally{
//            try {
//                new TarefaDAO().getClosedConnection();
//            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
//                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//        
//	}
    //METODO QUE CARREGA AS INFORMACOES DO GRID TAFERA E AGENDA
	private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
		jpSupAgenda.setEnabled(false); jpSupAgenda.setVisible(false);
		this.setSize(660, (620-altura));
        AgendamentoVO agendamentoVO = new AgendamentoVO();
        try {
            //CARREGA O GRID DE TAREFAS
        	if(modTarefa){
	            List<TarefaVO> tarefaVO = new ArrayList<>();
	            tarefaVO = new TarefaDAO().getAllTarefa();
	
	            modeloTarefa = (DefaultTableModel) jtTarefa.getModel();
	            for(TarefaVO trVO : tarefaVO)
	                modeloTarefa.addRow(new String[]{String.valueOf(trVO.getTarefaPk()), trVO.getDescricaoTarefa()});
	            
	            modTarefa = false;
        	}
            //CARREGA O GRID DA AGENDA
        	if(modAgenda){
	            agendamentoVO.setAno(Integer.valueOf(jycAno.getYear()));
	            List<AgendamentoVO> agendamentoVOs = new ArrayList<>();
	            agendamentoVOs = new AgendamentoDAO().getAllAgendamentoByAno(agendamentoVO);
	            
	            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
	            for(AgendamentoVO agVO : agendamentoVOs)//setForeground(new java.awt.Color(0, 0, 153));
	                modeloAgenda.addRow(new String[]{String.valueOf(agVO.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agVO.getDataAgendada()), (agVO.getHrAgendada() != "" ? agVO.getHrAgendada().substring(0, 5) : ""), agVO.getNomeCliente(), agVO.getNomeTarefa(), agVO.getStatusAgenda(), agVO.getNomeMotorista() });
	            
	            modAgenda = false;

        	}
        } catch (ClassNotFoundException | SQLException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(TabAgenda_Old_New.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                new TarefaDAO().getClosedConnection();
            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda_Old_New.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
    }                            
//	private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
//        
//        jpSupAgenda.setEnabled(false); jpSupAgenda.setVisible(false);
//        jpSupAgenda.setPreferredSize(new java.awt.Dimension(0, 0));
//        
//        AgendamentoVO agendamentoBean = new AgendamentoVO();
//        try {
//            //CARREGA O GRID DE TAREFAS
//            List<TarefaVO> tarefaBeans = new ArrayList<>();
//                tarefaBeans = new TarefaDAO().getAllTarefa();
//
//            modeloTarefa = (DefaultTableModel) jtTarefa.getModel();
//            for(TarefaVO trBean : tarefaBeans)
//                modeloTarefa.addRow(new String[]{String.valueOf(trBean.getTarefaPk()), trBean.getDescricaoTarefa()});
//            //CARREGA O GRID DA AGENDA
//            agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
//            List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
//            agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAno(agendamentoBean);
//            
//            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
//            for(AgendamentoVO agBean : agendamentoBeans)
//                modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), agBean.getHrAgendada(), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });
//                        
//        } catch (ClassNotFoundException | SQLException | IllegalAccessException | InstantiationException ex) {
//            Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
//        }finally{
//            try {
//                new TarefaDAO().getClosedConnection();
//            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
//                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//    
//    }                                    

    private void btoNovoActionPerformed(java.awt.event.ActionEvent evt) {
		jpSupAgenda.setEnabled(true); jpSupAgenda.setVisible(true);
		this.setSize(660, 620);
        try {
        	//CARREGA A DATA E HORA NA TELA QUANDO O CLIQUE VEM DO BOTAO NOVO
        	//QUANDO O CLIQUE FOR NO BOTAO ALTERAR VAI CARREGAR A DATA E HORA DO MEDOTO GETAGENDABYID
//        	if(botaoClicado != "btoAlterar"){
	        	//CARREGA O ID da AGENDA
	        	if(lblValorCodigo.getText() == ""){
	        		java.lang.String id = String.valueOf(new AgendamentoDAO().getUltimoId());
	        		lblValorCodigo.setText(String.valueOf( id.equals("null") ? 1 : (Integer.valueOf(id)+1) ));
	        	}
	        	if(jftDataAgendamento.getValue() == null){
	        		jftDataAgendamento.setText(new SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date()) );
	        	}
	        	if(jftHoraAgendamento.getValue() == null){
	        		jftHoraAgendamento.setText(new SimpleDateFormat("HH:mm").format(new java.util.Date()));
	        	}
//        	}
        	//CARREGA A COMBOBOX DE CLIENTE
        	if(jcbCliente.getItemCount() == 0){
        		jcbCliente.addItem("");
        		for(CadClienteVO cadClienteVO : new CadClienteDAO().getClienteByCombo()){
				//jcbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { cadClienteVO.getClientePk()+" - "+cadClienteVO.getNome() }));
        			jcbCliente.addItem(cadClienteVO.getClientePk()+" - "+cadClienteVO.getNome());
        		}
        	}
        	//CARREGA A COMBOBOX DE TAREFAS
        	if(jcbTarefa.getItemCount() == 0){
        		jcbTarefa.addItem("");
        		for(TarefaVO tarefaVO : new TarefaDAO().getAllTarefa() ){
        			jcbTarefa.addItem(tarefaVO.getTarefaPk()+" - "+tarefaVO.getDescricaoTarefa());
        		}
        	}
        	//CARREGA A COMBOBOX DE MOTORISTA
        	if(jcbMotorista.getItemCount() == 0){
        		jcbMotorista.addItem("");
        		for(CadMotoristaVO cadMotoristaVO : new CadMotoristaDAO().getMotoristaByCombo()){
        			jcbMotorista.addItem(cadMotoristaVO.getMotoristaPK()+" - "+cadMotoristaVO.getNome());
        		}
        		lblValorStatus.setText("Previsto");
        	}
        	if(botaoClicado == "btoAlterar"){
//        		getAgendaById(idAgenda);
        	}
        	
            btoNovo.setEnabled(false); btoSalvar.setEnabled(true); btoLocalizar.setEnabled(false); btoAlterar.setEnabled(false);
            btoCancelar.setEnabled(true); btoImprimir.setEnabled(false);
            
		} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e) {
			e.printStackTrace();
		}

    }                                       

    private void btoSalvarActionPerformed(java.awt.event.ActionEvent evt) {
    	//TRATA O REDIMENCIONAMENTO DA TELA PARA OCULTAR OS CAMPOS DO CADASTRO DA AGENDA
		jpSupAgenda.setEnabled(true); jpSupAgenda.setVisible(false);
		this.setSize(660, (620-altura));
		//CRIA O AGENDAMENTO DA BASE DE DADOS
        AgendamentoVO agendamentoVO = new AgendamentoVO();
        agendamentoVO.setAgendaPk(Integer.valueOf(lblValorCodigo.getText()));
        if(jftDataAgendamento.getText() != "  /  /    "){
        	try {
				agendamentoVO.setDataAgendada(new ConvertStringToDate().convertStringToDates(jftDataAgendamento.getText()));
			} catch (ParseException e) {
				e.printStackTrace();
			}
        }
        if(jftHoraAgendamento.getText() != "  :  ")
			try {
				agendamentoVO.setHoraAgendada(new java.sql.Time(new SimpleDateFormat("HH:mm").parse(jftHoraAgendamento.getText()).getTime()));
			} catch (ParseException e1) {
				e1.printStackTrace();
			}
        agendamentoVO.setClienteAFk(Integer.valueOf(jcbCliente.getSelectedItem().toString().substring(0, jcbCliente.getSelectedItem().toString().indexOf("-")).trim()) );
        agendamentoVO.setNomeCliente(jcbCliente.getSelectedItem().toString().substring(jcbCliente.getSelectedItem().toString().indexOf("-")).replace("-", "").trim() );
        agendamentoVO.setTarefaAFk(Integer.valueOf(jcbTarefa.getSelectedItem().toString().substring(0, jcbTarefa.getSelectedItem().toString().indexOf("-")).trim()) );
        agendamentoVO.setNomeTarefa(jcbTarefa.getSelectedItem().toString().substring(jcbTarefa.getSelectedItem().toString().indexOf("-")).replace("-", "").trim() );
        agendamentoVO.setStatusAgenda(lblValorStatus.getText());
        if(jcbMotorista.getSelectedIndex() > 0){
        	agendamentoVO.setMotoristaAFk(jcbMotorista.getSelectedItem().toString().substring(0, jcbMotorista.getSelectedItem().toString().indexOf("-")).trim());
        	agendamentoVO.setNomeMotorista(jcbMotorista.getSelectedItem().toString().substring(jcbMotorista.getSelectedItem().toString().indexOf("-")).trim() );
        }
                
        try {
			new AgendamentoDAO().insertAgendamento(agendamentoVO);
		} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e){ 
			e.printStackTrace();
		}finally{
			try {
				new AgendamentoDAO().getConnectionClose();
			} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e) {
				e.printStackTrace();
			}
		}
        btoNovo.setEnabled(false); btoSalvar.setEnabled(false);  btoLocalizar.setEnabled(true); btoAlterar.setEnabled(false);
        btoCancelar.setEnabled(true); btoImprimir.setEnabled(false);

    }                                         
    //METODO QUE REALIZA A LOCALIZACAO DO AGENDAMENTO CONFORME SELECAO DO GRID
    private void btoLocalizarActionPerformed(java.awt.event.ActionEvent evt) {                                           
		//		
        if(idAgenda == null){
        	JOptionPane.showMessageDialog(this, "Selecione no grid Agenda o compromisso e depois cliente em Localizar", "ControlMoto", JOptionPane.OK_OPTION);
        }else{
        	//TRATA O REDIMENCIONAMENTO DA TELA PARA OCULTAR OS CAMPOS DE ALTERACAO DA AGENDA
        	jpSupAgenda.setEnabled(true); jpSupAgenda.setVisible(true);
    		this.setSize(660, 620);
    		//CARREGA AS COMBOBOX DA TELA
    		try{
    	    	//CARREGA A COMBOBOX DE CLIENTE
    	    	if(jcbCliente.getItemCount() == 0){
    	    		jcbCliente.addItem("");
    	    		for(CadClienteVO cadClienteVO : new CadClienteDAO().getClienteByCombo()){
    				//jcbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { cadClienteVO.getClientePk()+" - "+cadClienteVO.getNome() }));
    	    			jcbCliente.addItem(cadClienteVO.getClientePk()+" - "+cadClienteVO.getNome());
    	    		}
    	    	}
    	    	//CARREGA A COMBOBOX DE TAREFAS
    	    	if(jcbTarefa.getItemCount() == 0){
    	    		jcbTarefa.addItem("");
    	    		for(TarefaVO tarefaVO : new TarefaDAO().getAllTarefa() ){
    	    			jcbTarefa.addItem(tarefaVO.getTarefaPk()+" - "+tarefaVO.getDescricaoTarefa());
    	    		}
    	    	}
    	    	//CARREGA A COMBOBOX DE MOTORISTA
    	    	if(jcbMotorista.getItemCount() == 0){
    	    		jcbMotorista.addItem("");
    	    		for(CadMotoristaVO cadMotoristaVO : new CadMotoristaDAO().getMotoristaByCombo()){
    	    			jcbMotorista.addItem(cadMotoristaVO.getMotoristaPK()+" - "+cadMotoristaVO.getNome());
    	    		}
    	    	}
    		}catch(SQLException | IllegalAccessException | InstantiationException | ClassNotFoundException e){
    			e.printStackTrace();
    		}finally{
    			try{
    				new TarefaDAO().getClosedConnection();
    			}catch(SQLException | IllegalAccessException | InstantiationException | ClassNotFoundException e){
    				e.printStackTrace();
    			}
    		}    		
    		//CARREGA OS DADOS DA SELECAO DA AGENDA PARA ALTERACAO
        	try{
        	AgendamentoVO agendamentoVO = new AgendamentoVO();
        	botaoClicado = "btoAlterar";
        	//
            agendamentoVO.setAgendaPk(Integer.valueOf(idAgenda));
            agendamentoVO = new AgendamentoDAO().getAgendamentoById(agendamentoVO);
            
            lblValorCodigo.setText(String.valueOf(idAgenda));
            jftDataAgendamento.setText(String.valueOf(new SimpleDateFormat("dd/MM/yyyy").format(agendamentoVO.getDataAgendada())));
            jftHoraAgendamento.setText(String.valueOf(new SimpleDateFormat("HH:mm").format(agendamentoVO.getHoraAgendada())));
            jcbCliente.setSelectedItem(agendamentoVO.getClienteAFk()+" - "+agendamentoVO.getNomeCliente());
            jcbTarefa.setSelectedItem(agendamentoVO.getTarefaAFk()+" - "+agendamentoVO.getNomeTarefa());
            lblValorStatus.setText(agendamentoVO.getStatusAgenda());
            jcbMotorista.setSelectedItem(agendamentoVO.getMotoristaAFk()+" - "+agendamentoVO.getNomeMotorista());
            		                       
			} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e) {
				e.printStackTrace();
			}finally{
    			try {
    				new AgendamentoDAO().getConnectionClose();
    			} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e) {
    				e.printStackTrace();
    			}
    		}
        }
        idAgenda = null;
        btoNovo.setEnabled(false); btoSalvar.setEnabled(false); btoLocalizar.setEnabled(false); btoAlterar.setEnabled(true);
        btoCancelar.setEnabled(false); btoImprimir.setEnabled(false);

    } 
    //METODO PARA FAZER A ATUALIZACAO DO AGENDAMENTO
    private void btoAlterarActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	//TRATA O REDIMENCIONAMENTO DA TELA PARA OCULTAR OS CAMPOS DE ALTERACAO DA AGENDA
		jpSupAgenda.setEnabled(false); jpSupAgenda.setVisible(false);
		this.setSize(660, (620-altura));
    	try{
	    	AgendamentoVO agendamentoVO = new AgendamentoVO();
	    	
	        agendamentoVO.setAgendaPk(Integer.valueOf(lblValorCodigo.getText()));
	        try{
	        	agendamentoVO.setDataAgendada(new ConvertStringToDate().convertStringToDates(jftDataAgendamento.getText()));
	        	agendamentoVO.setHoraAgendada(new java.sql.Time(new SimpleDateFormat("HH:mm").parse(jftHoraAgendamento.getText()).getTime()));
	        }catch(ParseException e){
	        	e.printStackTrace();
	        }
	        agendamentoVO.setClienteAFk(Integer.valueOf(jcbCliente.getSelectedItem().toString().substring(0, jcbCliente.getSelectedItem().toString().indexOf("-")).trim()));
	        agendamentoVO.setNomeCliente(jcbCliente.getSelectedItem().toString().substring(jcbCliente.getSelectedItem().toString().indexOf("-")).replace("-", "").trim() );
	        agendamentoVO.setTarefaAFk(Integer.valueOf(jcbTarefa.getSelectedItem().toString().substring(0, jcbTarefa.getSelectedItem().toString().indexOf("-")).trim()) );
	        agendamentoVO.setNomeTarefa(jcbTarefa.getSelectedItem().toString().substring(jcbTarefa.getSelectedItem().toString().indexOf("-")).replace("-", "").trim() );
	        agendamentoVO.setStatusAgenda(lblValorStatus.getText());
	        if(jcbMotorista.getSelectedIndex() > 0){
	        	agendamentoVO.setMotoristaAFk(jcbMotorista.getSelectedItem().toString().substring(0, jcbMotorista.getSelectedItem().toString().indexOf("-")).trim());
	        	agendamentoVO.setNomeMotorista(jcbMotorista.getSelectedItem().toString().substring(jcbMotorista.getSelectedItem().toString().indexOf("-")).replace("-", "").trim() );
	        }
	        
	        new AgendamentoDAO().updateAgendamento(agendamentoVO);
	        
			AgendamentoVO agendamentVO = new AgendamentoVO();

        	agendamentVO.setAno(Integer.valueOf(jftDataAgendamento.getText().substring(6)));
            List<AgendamentoVO> agendamentVOs = new ArrayList<>();

            agendamentVOs = new AgendamentoDAO().getAllAgendamentoByAno(agendamentVO);		
            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
            modeloAgenda.setNumRows(0);
            for(AgendamentoVO agVO : agendamentVOs)
            	modeloAgenda.addRow(new String[]{String.valueOf(agVO.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agVO.getDataAgendada()), (agVO.getHrAgendada() != "" ? agVO.getHrAgendada().substring(0, 5) : ""), agVO.getNomeCliente(), agVO.getNomeTarefa(), "<html><font color=red>"+agVO.getStatusAgenda()+"</color></html>", agVO.getNomeMotorista() });

		} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e) {
			e.printStackTrace();
		}finally{
			try {
				new AgendamentoDAO().getConnectionClose();
			} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e) {
				e.printStackTrace();
			}
		}
        btoNovo.setEnabled(true); btoSalvar.setEnabled(false); btoLocalizar.setEnabled(true); btoAlterar.setEnabled(false);
        btoCancelar.setEnabled(true); btoImprimir.setEnabled(false);

    }                                          
    //METODO QUE FAZ O CANCELAMENTO DO AGENDAMENTO
    private void btoCancelarActionPerformed(java.awt.event.ActionEvent evt) {
    	//Sim = 0 e Nao = 1
    	int confMsg = confMsg = JOptionPane.showConfirmDialog(this, "Deseja cancelar o lançameto de um novo compromisso?\nPara cancelar um compromisso já cadastrado\nselecione-o no grid Agenda.", "ControlMoto", JOptionPane.YES_NO_OPTION);
        if(confMsg == 0){
        	//TRATA O REDIMENCIONAMENTO DA TELA PARA OCULTAR OS CAMPOS DE ALTERACAO DA AGENDA
    		limpaCampos();
    		jpSupAgenda.setEnabled(false); jpSupAgenda.setVisible(false);
    		this.setSize(660, (620-altura));
            btoNovo.setEnabled(true); btoSalvar.setEnabled(false); btoLocalizar.setEnabled(true); btoAlterar.setEnabled(false);
            btoCancelar.setEnabled(true); btoImprimir.setEnabled(false);
        }else if(confMsg == 1 && idAgenda > 0){
        	int confCanclamento = confMsg = JOptionPane.showConfirmDialog(this, "Deseja cancelar o compromisso de código "+idAgenda+" ?", "ControlMoto", JOptionPane.YES_NO_OPTION);
        	if(confCanclamento == 0){
	        	AgendamentoVO agendamentoVO = new AgendamentoVO();
	        	botaoClicado = "btoCancelar";
	        	agendamentoVO.setAgendaPk(idAgenda);
	        	agendamentoVO.setStatusAgenda("Cancelado");
	        	try {
					new AgendamentoDAO().getCancelaAgendamentoById(agendamentoVO);
				} catch (IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e) {
					e.printStackTrace();
				}
	            JOptionPane.showMessageDialog(this, "Cancelamento realizado com sucesso", "ControlMoto", JOptionPane.OK_OPTION);
	            btoNovo.setEnabled(true); btoSalvar.setEnabled(false); btoLocalizar.setEnabled(true); btoAlterar.setEnabled(false);
	            btoCancelar.setEnabled(true); btoImprimir.setEnabled(false);
        	}
        }
    }                                           

    private void btoImprimirActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    //CONTROLA A BUSCA PELO DIA - MES - ANO
    private void jdcDiaPropertyChange(java.beans.PropertyChangeEvent evt) {                                      
        if(evt.getPropertyName() == "day"){
        	filtro = "day";
        	jrbTodos.setSelected(true);
            AgendamentoVO agendamentoBean = new AgendamentoVO();
            try {
                modeloAgenda.setNumRows(0);
                //CARREGA O GRID DA AGENDA CONFORME MUDANÇA DE DIA
                agendamentoBean.setDataAgendada(new java.sql.Date(new java.util.Date(String.valueOf(jycAno.getYear()+"/"+(jmcMes.getMonth() > 9 ? jmcMes.getMonth()+1 : ("0"+(jmcMes.getMonth()+1)))+"/"+jdcDia.getDay())).getTime()));
                List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
                agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByDia(agendamentoBean);

                modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
                modeloAgenda.setNumRows(0);
                for(AgendamentoVO agBean : agendamentoBeans)
                	modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });

            } catch (ClassNotFoundException | SQLException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    new TarefaDAO().getClosedConnection();
                } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                    Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }                                     
    //CONTROLA BUSCA POR MES E ANO
    private void jmcMesPropertyChange(java.beans.PropertyChangeEvent evt) {                                      
        if(evt.getPropertyName() == "month"){
        	filtro = "month";
        	jrbTodos.setSelected(true);
            AgendamentoVO agendamentoBean = new AgendamentoVO();
            try {
                //CARREGA O GRID DA AGENDA CONFORME MUDANÇA NO MES DO CALENDARIO
                agendamentoBean.setMes(Integer.valueOf(jmcMes.getMonth()+1));
                agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
                List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
                
                agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByMes(agendamentoBean);

                modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
                modeloAgenda.setNumRows(0);
                for(AgendamentoVO agBean : agendamentoBeans)
                	modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });

            } catch (IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    new TarefaDAO().getClosedConnection();
                } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                    Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    //CONTROLA BUSCA POR ANO E MES
    private void jycAnoPropertyChange(java.beans.PropertyChangeEvent evt) {                                      
        if(evt.getPropertyName() == "year"){
        	filtro = "year";
        	jrbTodos.setSelected(true);
            AgendamentoVO agendamentoBean = new AgendamentoVO();
            try {
                modeloAgenda.setNumRows(0);
                //CARREGA O GRID DA AGENDA CONFORME MUDANÇA DE ANO
                agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
                agendamentoBean.setMes(Integer.valueOf(jmcMes.getMonth()+1));
                List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
                agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAnoMes(agendamentoBean);

                modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
                modeloAgenda.setNumRows(0);
                for(AgendamentoVO agBean : agendamentoBeans)
                	modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });
                
            } catch (ClassNotFoundException | SQLException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    new TarefaDAO().getClosedConnection();
                } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                    Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }                                     
    //CONTROLA O CLIQUE NO GRID DA AGENDA
    private void jtAgendaMouseClicked(java.awt.event.MouseEvent evt) {
    	int linha = jtAgenda.getSelectedRow();
    	idAgenda = Integer.valueOf(jtAgenda.getValueAt(linha, 0).toString());
    	System.out.println(idAgenda);
    }                                       

    private void jmcMesMouseClicked(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void jrbPrevistoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        AgendamentoVO agendamentoBean = new AgendamentoVO();
        try {
            //CARREGA O GRID DA AGENDA CONFORME MUDANÇA NO MES DO CALENDARIO
            agendamentoBean.setDataAgendada(new java.sql.Date(new java.util.Date(String.valueOf(jycAno.getYear()+"/"+(jmcMes.getMonth() > 9 ? jmcMes.getMonth()+1 : ("0"+(jmcMes.getMonth()+1)))+"/"+jdcDia.getDay())).getTime()));
            agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
            agendamentoBean.setMes(Integer.valueOf(jmcMes.getMonth()+1));
            List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
            if(filtro == "day"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByDia(agendamentoBean);
            }else if(filtro == "month"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByMes(agendamentoBean);
            }else{
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAnoMes(agendamentoBean);
            }

            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
            modeloAgenda.setNumRows(0);
            for(AgendamentoVO agBean : agendamentoBeans)
            	if(agBean.getStatusAgenda().equals("Previsto"))
            		modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });

        } catch (IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                new TarefaDAO().getClosedConnection();
            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                           

    private void jrbAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        AgendamentoVO agendamentoBean = new AgendamentoVO();
        try {
            //CARREGA O GRID DA AGENDA CONFORME MUDANÇA NO MES DO CALENDARIO
            agendamentoBean.setDataAgendada(new java.sql.Date(new java.util.Date(String.valueOf(jycAno.getYear()+"/"+(jmcMes.getMonth() > 9 ? jmcMes.getMonth()+1 : ("0"+(jmcMes.getMonth()+1)))+"/"+jdcDia.getDay())).getTime()));
            agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
            agendamentoBean.setMes(Integer.valueOf(jmcMes.getMonth()+1));
            List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
            if(filtro == "day"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByDia(agendamentoBean);
            }else if(filtro == "month"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByMes(agendamentoBean);
            }else{
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAnoMes(agendamentoBean);
            }

            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
            modeloAgenda.setNumRows(0);
            for(AgendamentoVO agBean : agendamentoBeans)
            	if(agBean.getStatusAgenda().equals("Atrasado"))
            		modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });

        } catch (IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                new TarefaDAO().getClosedConnection();
            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                           

    private void jrbEnviadoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        AgendamentoVO agendamentoBean = new AgendamentoVO();
        try {
            //CARREGA O GRID DA AGENDA CONFORME MUDANÇA NO MES DO CALENDARIO
            agendamentoBean.setDataAgendada(new java.sql.Date(new java.util.Date(String.valueOf(jycAno.getYear()+"/"+(jmcMes.getMonth() > 9 ? jmcMes.getMonth()+1 : ("0"+(jmcMes.getMonth()+1)))+"/"+jdcDia.getDay())).getTime()));
            agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
            agendamentoBean.setMes(Integer.valueOf(jmcMes.getMonth()+1));
            List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
            if(filtro == "day"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByDia(agendamentoBean);
            }else if(filtro == "month"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByMes(agendamentoBean);
            }else{
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAnoMes(agendamentoBean);
            }

            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
            modeloAgenda.setNumRows(0);
            for(AgendamentoVO agBean : agendamentoBeans)
            	if(agBean.getStatusAgenda().equals("Enviado"))
            		modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });

        } catch (IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                new TarefaDAO().getClosedConnection();
            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                          

    private void jrbCanceladoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        AgendamentoVO agendamentoBean = new AgendamentoVO();
        try {
            //CARREGA O GRID DA AGENDA CONFORME MUDANÇA NO MES DO CALENDARIO
            agendamentoBean.setDataAgendada(new java.sql.Date(new java.util.Date(String.valueOf(jycAno.getYear()+"/"+(jmcMes.getMonth() > 9 ? jmcMes.getMonth()+1 : ("0"+(jmcMes.getMonth()+1)))+"/"+jdcDia.getDay())).getTime()));
            agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
            agendamentoBean.setMes(Integer.valueOf(jmcMes.getMonth()+1));
            List<AgendamentoVO> agendamentoBeans = new ArrayList<>();
            if(filtro == "day"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByDia(agendamentoBean);
            }else if(filtro == "month"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByMes(agendamentoBean);
            }else{
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAnoMes(agendamentoBean);
            }

            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
            modeloAgenda.setNumRows(0);
            for(AgendamentoVO agBean : agendamentoBeans)
            	if(agBean.getStatusAgenda().equals("Cancelado"))
            		modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });

        } catch (IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                new TarefaDAO().getClosedConnection();
            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                            

    private void jrbTodosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        AgendamentoVO agendamentoBean = new AgendamentoVO();
        try {
            //CARREGA O GRID DA AGENDA CONFORME MUDANÇA NO MES DO CALENDARIO
            agendamentoBean.setDataAgendada(new java.sql.Date(new java.util.Date(String.valueOf(jycAno.getYear()+"/"+(jmcMes.getMonth() > 9 ? jmcMes.getMonth()+1 : ("0"+(jmcMes.getMonth()+1)))+"/"+jdcDia.getDay())).getTime()));
            agendamentoBean.setAno(Integer.valueOf(jycAno.getYear()));
            agendamentoBean.setMes(Integer.valueOf(jmcMes.getMonth()+1));
            List<AgendamentoVO> agendamentoBeans = new ArrayList<>();

            if(filtro == "day"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByDia(agendamentoBean);
            }else if(filtro == "month"){
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByMes(agendamentoBean);
            }else{
            	agendamentoBeans = new AgendamentoDAO().getAllAgendamentoByAnoMes(agendamentoBean);
            }

            modeloAgenda = (DefaultTableModel) jtAgenda.getModel();
            modeloAgenda.setNumRows(0);
            for(AgendamentoVO agBean : agendamentoBeans)
            	modeloAgenda.addRow(new String[]{String.valueOf(agBean.getAgendaPk()), new SimpleDateFormat("dd/MM/yyyy").format(agBean.getDataAgendada()), (agBean.getHrAgendada() != "" ? agBean.getHrAgendada().substring(0, 5) : ""), agBean.getNomeCliente(), agBean.getNomeTarefa(), agBean.getStatusAgenda() });

        } catch (IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                new TarefaDAO().getClosedConnection();
            } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
                Logger.getLogger(TabAgenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void limpaCampos(){
    	lblValorCodigo.setText("");
    	jcbTarefa.setSelectedItem("");
    	lblNumeroOS.setText("");
    	jftDataAgendamento.setValue("");
    	jftHoraAgendamento.setValue("");
    	jcbCliente.setSelectedItem("");
    	jcbMotorista.setSelectedItem("");    	
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new TabAgenda().setVisible(true);
//            }
//        });
//    }
    //
    private ControlMoto telaControlMoto;
    
    static int openFrameCount = 5;
    static final int xOffset = 25, yOffset = 1;
    
    private int lagura = 640;
    private int altura = 144;
    static java.lang.String botaoClicado = null, filtro = null, caminho = null, separadorPath = null;
    static java.lang.Integer idAgenda = null;
    boolean modTarefa, modAgenda;
    //Variaveis para Tabela
    DefaultTableModel modeloTarefa, modeloAgenda;
    DefaultTableCellRenderer tcrDireta,tcrEsqueda,tcrCentro;
    TableColumnModel colModelAgenda, colModelTarefa;
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup bgOpcao;
    private javax.swing.JButton btoAlterar, btoCancelar, btoLocalizar, btoImprimir, btoNovo, btoSalvar;
    private javax.swing.JScrollPane jScrollPane1, jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JComboBox jcbCliente, jcbMotorista, jcbTarefa;
    private com.toedter.calendar.JDayChooser jdcDia;
    private javax.swing.JFormattedTextField jftDataAgendamento, jftHoraAgendamento;
    private com.toedter.calendar.JMonthChooser jmcMes;
    private javax.swing.JPanel jpDireito, jpEsquerdo, jpRodape, jpSupAgenda, jpSuperior;
    private javax.swing.JRadioButton jrbAtrasado, jrbCancelado, jrbEnviado, jrbPrevisto, jrbTodos;
    private javax.swing.JTable jtAgenda, jtTarefa;
    private javax.swing.JToolBar jtbBarraFerramenta;
    private com.toedter.calendar.JYearChooser jycAno;
    private javax.swing.JLabel lblCliente, lblCodigo, lblData, lblHora, lblMotorista, lblNumeroOS, lblStatus, lblValorCodigo,
    lblValorNumeroOS, lblValorStatus, lblTarefa, lblAtrasado;
    // End of variables declaration                   
}
